- src/main/resources/artifact-ignores.properties
I named the artifact-id of the jgiven-plugin jgiven-plugin - it should probably be jgiven...
As soon as this is merged i will make a new release with the new artifact-id.
> Ignored jgiven-plugin - renamed to jgiven

- src/main/resources/artifact-ignores.properties
As requested on https://groups.google.com/d/msg/jenkinsci-dev/Vxu26M5O2Ms/-g8hj_0XzXwJ
> Remove HiddenParameter

- src/main/resources/artifact-ignores.properties
This includes the changes proposed in pull request #12.
> Exclude several AWS-related plugin IDs.

- src/main/resources/artifact-ignores.properties
- src/main/resources/wiki-overrides.properties
Some of the overrides were in the deprecated list, or plugin developers have fixed their plugin metadata and released new versions! :tada:
> Add a few more deprecated plugins, and remove now-redundant wiki overrides

- src/main/resources/artifact-ignores.properties
Removing rally-bookkeeper from the update center as requested by @mike-rogers.
> Add rally-bookkeeper

- site/generate.sh
Kohsuke confirmed this is actually a bug, so offer the newest LTS release in LTS update centers.
> [FIX JENKINS-27560] Offer update to current LTS release in LTS UCs

- src/main/resources/artifact-ignores.properties
https://github.com/jenkinsci/ssh2easy-plugin/commit/2eec05b8e936ad2034dbd50575b9c18529dd480d#commitcomment-12078447
> Remove ssh2easy-plugin

- site/generate.sh
- src/main/java/org/jvnet/hudson/update_center/Main.java
Disable history creation for all but latest update site
@orrc WDYT?
> Add option to skip release history creation

- src/main/resources/wiki-overrides.properties
First batch. I'll try and process the list below later. Btw I think trying to put a dedicated comment each time is useful (has been here to double-check at least). Let me know if you think this is OK this way, or should better be one PR per removal.
> Remove some outdated wiki overrides

- src/main/resources/artifact-ignores.properties
[Request on the dev list](https://groups.google.com/d/msg/jenkinsci-dev/jBpDXiDVkS4/75T4hDPSDwAJ).
(Found the plugin through [hosting request](https://issues.jenkins-ci.org/browse/HOSTING-26))
CC @ryancblack
> Remove Fortify on Demand

- src/main/java/org/jvnet/hudson/update_center/MavenArtifact.java
- src/main/java/org/jvnet/hudson/update_center/Signer.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S2095 - Resources should be closed.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2095
Please let me know if you have any questions.
Faisal Hameed
> Code quality fix - Resources should be closed.

- src/main/java/org/jvnet/hudson/update_center/MavenArtifact.java
- src/main/java/org/jvnet/hudson/update_center/Signer.java
This reverts commit f38cfa29dc88e9ae27f4e0b90570b10a7ceb147e.
> Revert "Fixing squid:S2095 - Resources should be closed."

- src/main/resources/artifact-ignores.properties
See https://twitter.com/jenkins_release/status/708831455216992257
> Hide unknown plugin flyway-runner

- src/main/java/org/jvnet/hudson/update_center/MavenArtifact.java
- src/main/java/org/jvnet/hudson/update_center/Signer.java
Reverts jenkinsci/backend-update-center2#48 :-)
> Revert "Revert "Fixing squid:S2095 - Resources should be closed.""

- src/main/java/org/jvnet/hudson/update_center/Plugin.java
> Escape all the entities

- src/main/resources/artifact-ignores.properties
> Remove unknown release of build-timeout

- site/generate.sh
> Add update site for 2.7.x releases

- src/main/resources/artifact-ignores.properties
@orrc @rtyler 
Source: https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/PomView/releases/de/tsystems/mms/apm/performance-signature-ui/1.0.0/performance-signature-ui-1.0.0.pom
Asking for context in https://github.com/jenkinsci/performance-signature-dynatrace-plugin/commit/ab311d2bd023c7e90849b99651d2ca6974d21b6c#commitcomment-18273598
> Add performance-signature-ui

- src/main/resources/artifact-ignores.properties
Followup to #71 after the repo was fixed.
> Add performance-signature-ui back

- src/main/resources/artifact-ignores.properties
Attempting to fix https://groups.google.com/d/msg/jenkinsci-users/Xpe6oN5KDb0/UBHIfvUXAgAJ
> Add more broken releases

- site/generate.sh
> [FIX INFRA-885] Add tool installers to versioned update sites

- src/main/java/org/jvnet/hudson/update_center/Main.java
JSON file is more amenable for programmatic manipulation.
> What we call JSON is actually JSONP. Produce actual JSON.

- site/static/.htaccess
@daniel-beck caught me sneaking in a link change that of course didn't work
> Link update

- src/main/resources/artifact-ignores.properties
This plugin was renamed to jbehave jenkins plugin.
> [INFRA-800] Ignore jbehave hudson plugin

- site/LAYOUT.md
- site/README.md
- site/static/readme.html
Explain the layout of the update center and its files, including the newly added "actual JSON" file.
> Doc improvement

- site/static/.htaccess
There's some strange use of character classes and '+' operator...
> Fixed up regular expression match

- src/main/java/org/jvnet/hudson/update_center/Plugin.java
> Escape plugin title

- site/generate.sh
To be merged only once 2.32.1 is in the Maven index.
> Add 2.32 update site

- src/main/java/org/jvnet/hudson/update_center/Main.java
- src/main/resources/warnings.json
- src/test/java/org/jvnet/hudson/update_center/WarningsTest.java
List of warnings is initialized with recent plugin vulnerabilities
---
Companion PR to https://github.com/jenkinsci/jenkins/pull/2680 and https://github.com/jenkins-infra/backend-jenkins-plugin-info-plugin/pull/11
> [INFRA-1022] Add support for warnings shown to Jenkins admins

- src/main/resources/warnings.json
https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2017-02-01
> Add Jenkins 2.44 warning

- src/main/resources/artifact-ignores.properties
> Need to spin another workflow-multibranch

- src/main/resources/artifact-ignores.properties
> Another typo

- src/main/resources/artifact-ignores.properties
> Return SCM APi 2.0.x and friends to Update Center

- src/main/resources/artifact-ignores.properties
> Ignore broken testodyssey-execution-1.1 release

- src/main/resources/artifact-ignores.properties
Broken hpi file in Artifactory
> Ignore bitbucket-build-status-notifier-1.3.2

- Jenkinsfile
> Add an update site generation to the Jenkinsfile

- src/main/resources/artifact-ignores.properties
> Release broken by JENKINS-42739

- src/main/java/org/jvnet/hudson/update_center/Main.java
- src/main/java/org/jvnet/hudson/update_center/MavenArtifact.java
- src/main/java/org/jvnet/hudson/update_center/Plugin.java
There are three related optimizations in this PR:
1. Only parse the plugin POM on demand rather than `Plugin` creation.
1. Use the artifact modification date rather than the `MANIFEST.MF` change time inside the `hpi`.
1. Do not include `title` or `wiki` in `release-history.json` entries older than a month
The **first change** should be fairly straightforward and comes with no change in behavior, it just enables the third one.
The **second change** will change almost all timestamps due to a time zone dependency I haven't figured out. Most release times change by 0-14 hours ± 5 minutes. Some, e.g. Surround SCM, change by weeks, something I don't understand and asked the maintainer at https://github.com/jenkinsci/Surround-SCM-plugin/commit/90a4e49f927e9444dceb4eaf54b897a2c414e7c7#commitcommen …
> [WIP] Optimize release history generation and timestamps

- src/main/resources/artifact-ignores.properties
https://issues.jenkins-ci.org/browse/INFRA-1108
CC @evernat @orrc @madsnielsen
> [FIX INFRA-1108] Remove first-plugin

- src/main/resources/artifact-ignores.properties
https://wiki.jenkins-ci.org/display/JENKINS/Vessel+plugin
https://groups.google.com/d/msg/jenkinsci-dev/L34eAMMWA5o/-AxtRdGsAAAJ
> Ignore vessel plugin

- src/main/java/org/jvnet/hudson/update_center/MavenArtifact.java
@kwhetstone may care, not sure.
> More specific error messages when resolution fails

- site/generate.sh
> [FIX INFRA-1215] 'stable' should be newest, not oldest

- src/main/resources/warnings.json
> Real pattern for Groovy label assignment plugin

- src/main/resources/warnings.json
fixed by https://github.com/jenkinsci/splunk-devops-plugin/pull/3
changes:
https://github.com/jenkinsci/splunk-devops-plugin/compare/jenkinsci:release/1.5.2...1.5.3
> fixed SECURITY-479 https://github.com/jenkinsci/splunk-devops-plugin/3

- src/main/resources/artifact-ignores.properties
- src/main/resources/warnings.json
Change-Id: Iacf4142b8fd8156d5710c8838280ae85fc1813e6
> Restore integrity-plugin distribution

- src/main/resources/artifact-ignores.properties
- src/main/resources/warnings.json
and customized update center warning as recommended by @daniel-beck here:
https://github.com/jenkins-infra/repository-permissions-updater/pull/492#issuecomment-341496738
> JENKINS-43637 Removed blacklisting from PostBuildScript plugin

- src/main/resources/artifact-ignores.properties
- src/main/resources/warnings.json
Issue: https://issues.jenkins-ci.org/browse/SECURITY-489
Just released: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/proc-cleaner-plugin/2.0/
Compatibility notes: https://wiki.jenkins.io/display/JENKINS/Process+Cleaner+Plugin
> [SECURITY-489] Renew distribution of proc-cleaner-plugin

- src/main/java/org/jvnet/hudson/update_center/Signer.java
Rerun of https://github.com/jenkins-infra/backend-update-center2/pull/97 for [INFRA-1428](https://issues.jenkins-ci.org/browse/INFRA-1428)
> [INFRA-1428] Reduce required validity to 15 days

- src/main/resources/artifact-ignores.properties
CC @daniel-beck @warden https://issues.jenkins-ci.org/browse/JENKINS-48357
> [JENKINS-48357] - Fix the JIRA 2.5.1 blacklist string

- src/main/resources/artifact-ignores.properties
See the justification in https://issues.jenkins-ci.org/browse/INFRA-1531
@daniel-beck
> [INFRA-1531] - Depublish the Jenkins Tracker Plugin

- src/main/resources/artifact-ignores.properties
https://github.com/jenkinsci/node-sharing-plugin/pull/65
CCing owner, @pjanouse.
> Stop distribution of foreman-node-sharing in favour of node-sharing

- pom.xml
- src/main/java/org/jvnet/hudson/update_center/MavenArtifact.java
- src/main/java/org/jvnet/hudson/update_center/Signer.java
Provides the infra change corresponding to https://github.com/jenkinsci/jenkins/pull/3356
> Add SHA-256 and SHA-512 digests, SHA-512/RSA signature

- src/main/resources/artifact-ignores.properties
See https://github.com/jenkins-infra/update-center2/pull/199
FYI @billmanhillman @greg-peters
> Suspend distribution of websphere-deployer 1.5.5 + 1.5.6

- src/main/resources/artifact-ignores.properties
Revert #202 as I missed the requested fix in an unrelated looking commit. Sorry @Joeoffenberg!
> Restore distribution of influxdb-query

- src/main/java/org/jvnet/hudson/update_center/GitHubSource.java
Work around https://github.com/kohsuke/github-api/pull/446
> Work around pagination bug in github-api

- site/generate-htaccess.sh
Fixes https://gist.github.com/daniel-beck/41a3f63c5bfd519d0b052b15e7ba1852#file-gistfile1-txt-L33
Amends https://github.com/jenkins-infra/update-center2/pull/208
> Fix redirects of weekly

- site/test/redirects.sh
Test cases for https://github.com/jenkins-infra/update-center2/blob/master/site/generate-htaccess.sh
> Add "test" for htaccess

- src/main/java/org/jvnet/hudson/update_center/Plugin.java
- src/main/java/org/jvnet/hudson/update_center/XmlCache.java
> Cache XML contents

- src/main/java/org/jvnet/hudson/update_center/Plugin.java
Impact on current content:
https://gist.github.com/daniel-beck/857eb6769d382b8377a69e7d5039dbd8
@jglick
> Let HTML sanitizer handle <?jelly>, prohibit block elements

- pom.xml
- site/generate.sh
- src/main/java/org/jvnet/hudson/update_center/ArtifactSource.java
- src/main/java/org/jvnet/hudson/update_center/ArtifactoryArtifactSource.java
- src/main/java/org/jvnet/hudson/update_center/DefaultMavenRepositoryBuilder.java
- src/main/java/org/jvnet/hudson/update_center/GitHubSource.java
- src/main/java/org/jvnet/hudson/update_center/Main.java
- src/main/java/org/jvnet/hudson/update_center/XmlCache.java
- src/test/java/HPIResolver.java
- src/test/java/ListExisting.java
- src/test/java/ListPluginsAndVersions.java
Save a bunch of time downloading the Artifactory index etc. by generating multiple update sites in the same invocation.
> Allow building multiple update sites with one invocation

- src/main/java/org/jvnet/hudson/update_center/IndexHtmlBuilder.java
Surprisingly often I want to know when which version of a plugin was released. So add this information to the index of all versions. Since it's not really important, in a tool tip is enough IMO.
> Add tool tip with release date to versions list

- site/publish.sh
> [INFRA-1730]

- site/generate-htaccess.sh
- site/generate.sh
- site/test/redirects.sh
[INFRA-1765](https://issues.jenkins-ci.org/browse/INFRA-1765)
> [INFRA-1765] Expose plugin-releases.json at the root level

- site/generate.sh
> [INFRA-1765] Fix file name

- src/main/java/org/jvnet/hudson/update_center/ArtifactoryArtifactSource.java
> Improve robustness in case of invalid URLs

- src/main/java/org/jvnet/hudson/update_center/Main.java
- src/main/java/org/jvnet/hudson/update_center/MavenRepositoryImpl.java
Plus some better logging if we set a filter.
> Reset plugin filters between batch executions

- src/main/resources/label-definitions.properties
Added labels for https://wiki.jenkins.io/display/JENKINS/QRebel+Plugin
> Labels: added QRebel plugin and its labels

- src/main/resources/warnings.json
https://github.com/jenkinsci/testfairy-plugin/commit/f37510f5121f166786e1374d8bd4c673a5ebb8d2
@giltsl
> [SECURITY-1062] TestFairy 4.17.2 has a fix

- src/main/resources/artifact-ignores.properties
Broken release that prevents listing on https://updates.jenkins-ci.org/download/plugins/
> Blacklist localization-zh-cn-1.0.5

- src/main/resources/artifact-ignores.properties
configuration-as-code-support is no more!
> deprecate configuration-as-code-support

- src/main/resources/label-definitions.properties
Sets the labels for workflow-cps-global-lib-http
> workflow-cps-global-lib-http labels

- src/main/resources/warnings.json
changes the versions pattern bcz of warning
> changes the versions pattern

- src/main/resources/artifact-ignores.properties
As noted in https://github.com/jenkins-infra/repository-permissions-updater/pull/1232#issuecomment-513274443
@batmat @daniel-beck
> Rename paranoia to extended-security-settings

- README.md
- src/main/resources/label-definitions.properties
Assuming merge of https://github.com/jenkinsci/jenkins/pull/3982.
> [JENKINS-37862] Category for build-symlink

- src/main/resources/artifact-ignores.properties
[INFRA-2347](https://issues.jenkins-ci.org/browse/INFRA-2347)
See also https://github.com/jenkins-infra/repository-permissions-updater/pull/1350
CC @olamy
> [INFRA-2347]

- src/main/resources/artifact-ignores.properties
should have been version 2.6.3
> suppress cmakebuilder-3.6.3

- src/main/resources/warnings.json
> Changed pattern to match vulnerable versions

- src/main/resources/allowed-labels.properties
Aligns with the current adoption process: https://github.com/jenkins-infra/jenkins.io/pull/2875
> Remove the adopt-me label from the list of whtelisted ones, use adopt-this-plugin

- src/main/resources/warnings.json
According to the maintainers, this has been addressed in 0.0.17.
I still need to confirm that is the case.
Generated regex, so slightly suboptimal.
> [SECURITY-946] Update regex

- pom.xml
- src/main/java/org/jvnet/hudson/update_center/MavenArtifactSource.java
- src/test/java/org/jvnet/hudson/update_center/MavenArtifactSourceTest.java
* Use and test processing files from ZipInputStream
* make sure streams get closed with try-with-resources
> Attempt to fix the random too many files open errors

- src/main/resources/warnings.json
The PR #317 was merged, but due to the master branch being changed between the creation and the merge, the patch was not applied at the correct location.
- https://github.com/jenkins-infra/update-center2/pull/317/files
- https://github.com/jenkins-infra/update-center2/commit/12ef2f5dc161c3f84792731951fb8f73da2fed91
:'(
> [SECURITY-957][SECURITY-1063] Correction of incorrectly merged PR

- src/main/resources/artifact-ignores.properties
FYI: @oleg-nenashev @Jetersen 
https://github.com/jenkinsci/configuration-as-code-plugin/issues/1339
> Blacklist jcasc 1.37

- src/main/resources/wiki-overrides.properties
As discussed in https://issues.jenkins-ci.org/browse/INFRA-2595
> [INFRA-2595] Add Synopsys Polaris plugin to wiki-overrides.properties

- src/main/java/io/jenkins/update_center/HPI.java
Very minor optimization of something that showed up in a recent profiling run.
> Reuse this regex for all instances of the class

- resources/allowed-github-topics.properties
https://github.com/search?q=topic%3Atheme+org%3Ajenkinsci+fork%3Atrue
CC @timja @tobix
> Allow the "theme" plugin label in the Update Center

- resources/allowed-github-topics.properties
For Cloudify, as well as (potentially) others
> Added "orchestration" category

- resources/artifact-ignores.properties
Same problem as 2.247, see e.g. https://github.com/jenkins-infra/jenkins.io/pull/3545
> Do not publish jenkins 2.247

- site/generate-htaccess.sh
- site/test/test.sh
Some assertions were really off 😭 
Thanks to @timja for the bug report.
> Fix off-by-one bug in htaccess redirect rules

- site/generate-htaccess.sh
Documentation for 302 being the default: http://httpd.apache.org/docs/2.2/rewrite/flags.html#flag_r
> Use HTTP 302 Found for dynamic redirects, as these may change over time

- site/generate-htaccess.sh
- site/test/test.sh
Looks like I confused LTS and weekly redirect rules. #403 fixed it for weeklies, this fixes it for LTS. (+ copy and paste fix)
> Fix LTS redirects

- pom.xml
- src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
- src/main/java/io/jenkins/update_center/Popularities.java
- Remove Gson from GitHub repo processing
- Switch Popularities from json-lib to fastjson
----
Supersedes https://github.com/jenkins-infra/update-center2/pull/388
> Further standardize on fastjson

- site/generate.sh
> Update to 3.3.1

- site/static/readme.html
Shown at the bottom of https://updates.jenkins.io/
> Fix footer formatting

- resources/artifact-ignores.properties
- resources/deprecations.properties
Followup to #377 and #390.
@stevespringett PTAL
> Suspend distribution of fortify-cloudscan-jenkins-plugin, add deprecation URL

- site/generate.sh
> Skip sanity check for skipped generated versions

- src/main/java/io/jenkins/update_center/json/TieredUpdateSitesGenerator.java
Right now, https://updates.jenkins.io/tiers.json indicates there are plugins depending on 2.236, 2.238, 2.240, 2.243, and 2.248, but we don't generate a 2.249.1 tier for LTS, even though this version has been released earlier today and is "visible" to this tool. `https://updates.jenkins.io/update-center.actual.json?version=2.249.1` redirects to 2.235.5.
This change should fix that by adding the lowest LTS release necessary when a plugin has a dependency on a weekly release.
I would guess this just wasn't noticeable recently because developers tend to depend on a ".1" release fairly quickly, masking this problem for all lines that were supported already when I introduced this change a few months ago.
> Include next higher LTS as a baseline for weekly dependencies

- resources/warnings.json
https://github.com/jenkins-infra/jenkins.io/pull/3704
> [SECURITY-1961] Rephrase warning

- site/generate.sh
- src/main/java/io/jenkins/update_center/Signer.java
- src/main/java/io/jenkins/update_center/util/Environment.java
[INFRA-2732](https://issues.jenkins-ci.org/browse/INFRA-2732)
> [INFRA-2732] Allow overriding the minimum validity duration

- resources/artifact-ignores.properties
Forgot to include these in the warnings update 😅
> Suspend persona (SECURITY-2046) and nerrvana (SECURITY-2097)

- resources/warnings.json
https://plugins.jenkins.io/soapui-pro-functional-testing/
https://www.jenkins.io/security/advisory/2020-09-01/#SECURITY-1631 (2) is fixed since version 1.6. The version 1.6 is released.
> [SECURITY-1631-2] The vulnerability is fixed in 1.6

- resources/warnings.json
The maintainers informed us that this issue was resolved.
Looks like https://github.com/jenkinsci/klocwork-plugin/commit/44e860003a3bd4c8323f6572dc9d9ddf3d2bba8f is the commit with the fix.
> [SECURITY-1831] Record that the issue was fixed in 2020.3.1

- site/generate.sh
No need to download this every few minutes.
> [INFRA-2754] Cache tool download

- resources/artifact-ignores.properties
See https://github.com/jenkinsci/jenkins/pull/5049
https://github.com/jenkins-infra/update-center2/pull/364
cc @jglick
> Stop ignoring sshd

- resources/warnings.json
It was fixed in https://github.com/jenkinsci/flaky-test-handler-plugin/pull/14
> Issue [SECURITY-1763] was fixed in version 1.1.0

- resources/artifact-ignores.properties
https://cve.mitre.org/cgi-bin/cvename.cgi?name=2020-2285
Thanks!
> Removing Liquibase Runner 1.4.7 due to CVE

- CHANGELOG.adoc
- site/generate.sh
Origin branch, delete after merge.
> Use version 3.7, add changelog

- resources/allowed-github-topics.properties
- resources/label-definitions.properties
Enable the observability topic
> Enable the observability GitHub topic

- resources/deprecations.properties
This avoids redirects for the deprecation links and saves a few bytes of the JSON size.
> Normalize issues URLs

- resources/warnings.json
https://groups.google.com/g/jenkinsci-dev/c/kAoHcVFZWGQ
Fix was in https://github.com/jenkinsci/nomad-plugin/pull/48
> SECURITY-1058 was resolved in nomad plugin 0.6.2

- resources/artifact-ignores.properties
- resources/warnings.json
https://issues.jenkins.io/browse/INFRA-2997
> [INFRA-2997] Restore zap-pipeline

- pom.xml
- src/main/java/io/jenkins/update_center/DefaultMavenRepositoryBuilder.java
- src/main/java/io/jenkins/update_center/GitHubSource.java
- src/main/java/io/jenkins/update_center/HPI.java
- src/main/java/io/jenkins/update_center/IssueTrackerSource.java
- src/main/java/io/jenkins/update_center/MaintainersSource.java
- src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java
> Set SpotBugs threshold to low, address issues

- resources/warnings.json
These were an intermediate state during security fix metadata authoring, not the final state. Date wrong, version patterns wrong, etc 😭
> Fix 2021-08-31 security warnings

- resources/artifact-ignores.properties
https://issues.jenkins.io/browse/INFRA-3067
> [INFRA-3067] Suspend distribution of credentials 2.6

- resources/deprecations.properties
Like #525, but for jenkinsci/jenkins#5560.
> Formally deprecating plugins left behind in jenkinsci/jenkins#5560

- resources/artifact-ignores.properties
Security issue is JIRA SECURITY-2525
> Removing squash4jenkins due to security issue

- resources/artifact-ignores.properties
This plugin is no longer maintained by the incapptic Connect Team.
> deprecated incapptic-connect-uploader-plugin

- resources/artifact-ignores.properties
Amends #574
Origin branch, delete on merge.
> Fix artifact ID

- resources/artifact-ignores.properties
This eggplant-plugin had been deprecated. We would like to request to remove the plugin from Jenkins plugin Update Center
> Update artifact-ignores.properties - Remove eggplant-plugin 

- resources/artifact-ignores.properties
https://github.com/jenkins-infra/jenkins.io/pull/5036
> Suspend phoenix-autotest

- resources/warnings.json
This is kinda weird otherwise.
@Kevin-CB PTAL
> Rephrase the title of SECURITY-2617 to make sense

- resources/artifact-ignores.properties
> Supersede ui-samples-plugin

- resources/artifact-ignores.properties
see https://groups.google.com/g/jenkinsci-dev/c/1bIdZr8P_Ms
> ignore monkit-plugin

- resources/artifact-ignores.properties
> block instance-identity 3.2

- resources/warnings.json
Resolves https://github.com/jenkins-infra/helpdesk/issues/3050
> [SECURITY-2521] Note fix in version 351

- resources/warnings.json
https://github.com/jenkins-infra/jenkins.io/pull/5290
@Kevin-CB
> Fix last version for SECURITY-2536

- resources/artifact-ignores.properties
[JENKINS-69164](https://issues.jenkins.io/browse/JENKINS-69164)
CC @MarkEWaite @halkeye as the more active board members.
CC @duyluonganh @HieuBui419 who seem to be the plugin maintainers.
> [JENKINS-69164] Suspend distribution of katalon plugin

- src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java
Amends #569. Prevents https://github.com/jenkins-infra/helpdesk/issues/3095 in upcoming releases.
Code is optimized for the minimal diff in `DirectoryTreeBuilder` (i.e., left the problems with the old code alone): https://github.com/jenkins-infra/update-center2/compare/85cf683e8b5e82832a9030d917b49bae2cdb8920...b8b5f39b2f29c8dd9469a34e0d7419efa9ca4ae4#diff-5d3a4a8d8349c3ec3298fab3093427096b8b73f7b5d791e41b76d4016b7a5302
> Fix hardlink creation

- README.adoc
- site/generate.sh
- src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
* Remove support for old base64 formatted cache
* Remove support for fixed tier update sites (~2.249.x and older)
> Clean up code and docs a bit

- resources/warnings.json
Fixes https://github.com/jenkins-infra/helpdesk/issues/3286.
As usual, we need to confirm the issues are fixed first.
> SECURITY-2048 and -2812 are resolved in 387.v938a_ecb_f7fe9

- resources/artifact-ignores.properties
accidental deploy of blueocean-1.26.1-JDK11TEST
> add blueocean-1.26.1-JDK11TEST to ignore list

- resources/artifact-ignores.properties
https://github.com/jenkinsci/ascii-magician-plugin/issues/1
Looks like the maintainers are security researchers and decided to spam project infrastructure instead of just setting up their own local update sites.
> Suspend ascii-magician

- resources/warnings.json
Corrected by https://github.com/jenkinsci/performance-plugin/commit/b0b4e742529208d7eaefc35ef200472cc82134c9
> SECURITY-2394 is resolved in 916.v0f63142e4c07

- src/main/java/io/jenkins/update_center/ArtifactCoordinates.java
- src/main/java/io/jenkins/update_center/BaseMavenRepository.java
- src/test/java/io/jenkins/update_center/ArtifactCoordinatesTest.java
Fixes https://github.com/jenkins-infra/helpdesk/issues/3317 
May have merge conflicts with https://github.com/jenkins-infra/update-center2/pull/647/
> Only publish plugin versions starting with a number

- resources/artifact-ignores.properties
Announcement: https://blog.testproject.io/2022/11/17/testproject-end-of-life-your-questions-answered
> testproject - service discontinued

- resources/artifact-ignores.properties
thundra-foresight plugin is no longer in service
> Deprecate and suspend `thundra-foresight`

- resources/artifact-ignores.properties
Use proper separator in readme section
> Update instructions of artifact-ignores.properties

- resources/warnings.json
Addressed in https://github.com/jenkinsci/lucene-search-plugin/commit/828f79fedbe3da08b17937a85b98b5d7f499a8dd
> [SECURITY-3013] Mark addressed since 398.v3dfa_cb_223984

- resources/warnings.json
Updating Regex Pattern to remove the SECURITY-1450 vulnerability. 
https://www.jenkins.io/security/advisory/2019-10-16/#SECURITY-1450
This issue has been replaced in the new Delphix v3.0.1 release. 
We now leverage Secret text to authenticate via API Keys.
The new regex should target all pre-v3 releases.
> Remove SECURITY-1450 for v3+ releases - Updated regex pattern

- resources/artifact-ignores.properties
https://github.com/jenkins-infra/helpdesk/issues/3742
> Suspend distribution of nexus-jenkins-plugin due to license issue

- resources/artifact-ignores.properties
Warning removal PR: https://github.com/jenkins-infra/update-center2/pull/750
> Restore `batch-task` distribution

- resources/warnings.json
Solved in version
See 3.0 https://github.com/jenkinsci/oic-auth-plugin/releases/tag/oic-auth-3.0
> Resolving SECURITY-2979

- site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2142644635
This PR is a follow-up of #784 and is were review should happen (cc @daniel-beck ) as we use the PR here to test changed in a dummy freestyle job in trusted.ci.
The goal is the following:
> While working on https://github.com/jenkins-infra/update-center2/pull/777 for the [Update Center migration to a mirror system](https://github.com/jenkins-infra/helpdesk/issues/2649), we realized the following problems with the current `publish.sh` script:
> 
> - It's hard to test a change until it's in production => we would want to enable/disable some steps to only focus testing on others in order to have enough confidence to merge PRs without breaking the production (neither requiring a fully fledged staging …
> chore(publish) abstract environment variables and introduce feature flag

- site/publish.sh
Related to https://issues.jenkins.io/browse/JENKINS-73761 and https://github.com/jenkins-infra/helpdesk/issues/2649
> hotfix(publish) use checksum instead of size to avoid ignoring latestCore.txt

- site/publish.sh
> hotfix(publish) ensure htaccess data beetween 2 httpd file shares

- site/publish.sh
This reverts https://github.com/jenkins-infra/update-center2/pull/819
Because the rsync fails with:
```
symlink has no referent: "/home/jenkins/agent-workspace/workspace/update_center/www2/current/updates"
```
> Revert "chore(wrappers/publish) ensure Apache has access to symlinked folders…"

- CODEOWNERS
@dduportal WDYT?
CC @Kevin-CB.
> Add CODEOWNERS for warnings metadata and the publishing script

- site/publish.sh
Reverts #825 and https://github.com/jenkins-infra/update-center2/commit/63c3ceffc21404c35641322a608b7fccf3807ff4
> chore(wrappers/publish) revert changes related to PR #825

- site/publish.sh
Reverts jenkins-infra/update-center2#827 as we need to work on the SSH hist keys of the rsync service
> Revert "chore(wrappers/publish) add 3 new rsync targets on the new data service"

- site/publish.sh
Ref. https://github.com/jenkins-infra/helpdesk/issues/4402#issuecomment-2506471357
Blocked by https://github.com/jenkins-infra/crawler/pull/155
> chore(wrappers/publish) remove all azcopy/azsync tasks (replaced by rsync on NFS) as it is unreliable

- resources/artifact-ignores.properties
https://issues.jenkins.io/browse/JENKINS-75187
> Block `ec2@1822.v87175d209b_b_5`

- src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java
Implement https://github.com/jenkins-infra/repository-permissions-updater/pull/2891#issuecomment-1290221864
Waiting for https://github.com/jenkins-infra/repository-permissions-updater/issues/2911 to proceed.
> Mark plugins without maintainers as up for adoption

- resources/warnings.json
see https://github.com/jenkinsci/avatar-plugin/releases/tag/19.vde06e8031618
> Resolve SECURITY-1099 (avatar)

- resources/warnings.json
Replaces https://github.com/jenkins-infra/update-center2/pull/847 and https://github.com/jenkins-infra/update-center2/pull/848
> [SECURITY-2774][SECURITY-2786] Note fixes in jira-steps plugin

- resources/warnings.json
Release 19.v7d532cccd44e of favorite-view plugin fixed the security vulnerability
> mark SECURITY-3201 as resolved

- resources/warnings.json
> Add `firstVersion` to SECURITY-3588

- site/publish.sh
Ref. https://github.com/jenkins-infra/helpdesk/issues/4758
> feat(publish) stop publishing on the 'unsecured' (HTTP) web services as HTTPS is enforced

- site/publish.sh
Ref. https://github.com/jenkins-infra/helpdesk/issues/4773#issuecomment-3252660608
This PR changes the publication process of new plugins to copy directly files to get.jenkins.io and archives.jenkins.io:
- `get.jenkins.io` reference directory (used by mirrorbits) is already in Azure (in the mounted NFS directory). We are using it since 2 weeks with no issues: there is no need to publish (plugin) files to the AWS `pkg.origin` VM.
- The "mirror script" [`sync-recent-releases.sh`](https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/templates/mirror-scripts/sync-recent-releases.sh.erb) logic is added in the wrapper `publish.sh` script here instead of being called remotely on the `pkg.origin` VM
- Less data to transfer as we now only copy freshly released files => …
> chore(wrapper/publish) directly publish to archives.jio and get.jio instead of going through pkg.origin.jio VM
