jenkins-infra/update-center2

src/main/resources/artifact-ignores.properties
As stated on https://wiki.jenkins-ci.org/display/JENKINS/Rational+Team+Concert+Plugin for years:
> Deprecated since core 1.480.3.  Use Team Concert Plugin instead.
=> Remove rtc

src/main/resources/artifact-ignores.properties
Related to #14, I went through the entire plugin list and went searching through artifact IDs, GitHub repos, old wiki pages and ended up with this list of (mostly) unreported artifact ID renames.
I still have a few more to look into more closely...
=> Add more deprecated/renamed plugins to exclude from the Update Centre.

src/main/resources/wiki-overrides.properties
I changed the update centre code to be more strict about wiki URLs, and examined every single error that resulted...
Some plugins do have the correct URL in the POM, but haven't been released yet, a few are simple URL typos, but the majority specify no wiki URL in the POM.
Ideally somebody would also now make pull requests for most of the plugins on the list...
=> Add a lot of wiki overrides for plugins with incorrect/missing URLs.

src/main/resources/wiki-overrides.properties
Each of these plugins will, after #20 is merged, still be available in the UC, but the URL will point to the "[Plugin Documentation Missing](https://wiki.jenkins-ci.org/display/JENKINS/Plugin+Documentation+Missing)" wiki page, which tells users what the situation is, and warns that this plugin will be removed in future if no wiki page is added.
=> Add temporary overrides for plugins with no wiki page at all.

pom.xml, src/main/java/org/jvnet/hudson/update_center/AlphaBetaOnlyRepository.java, src/main/java/org/jvnet/hudson/update_center/ConfluencePluginList.java, src/main/java/org/jvnet/hudson/update_center/LatestLinkBuilder.java, src/main/java/org/jvnet/hudson/update_center/Main.java, src/main/java/org/jvnet/hudson/update_center/MavenRepository.java, src/main/java/org/jvnet/hudson/update_center/MavenRepositoryImpl.java, src/main/java/org/jvnet/hudson/update_center/Plugin.java, src/main/java/org/jvnet/hudson/update_center/TruncatedMavenRepository.java, src/main/java/org/jvnet/hudson/update_center/VersionCappedMavenRepository.java, src/test/java/org/jvnet/hudson/update_center/ConfluencePluginListTest.java
The criteria for inclusion are:
- Plugins must specify a Jenkins wiki URL in their `pom.xml`, via the `<url>` tag
- The wiki page must exist on the Jenkins wiki
- The wiki page must be a child of the "Plugins" page
Also accepted are:
- Wiki short URLs (e.g. `/x/GYCGAQ`)
- Wiki URLs with a numeric ID (e.g. `/pages/viewpage.action?pageId=60915753`)
- URLs which have legacy URL prefixes (e.g. non-HTTPS, wiki.hudson-ci.org)
- URLs ending with a trailing slash
Plugins not meeting these criteria will not be included in the Update Centre JSON file, or will have an empty `wiki` value in the release history JSON file.
As before, plugins may also be excluded via the `artifact-ignores.properties` file, or if a plugin does specify a valid wiki page, but that wiki page has the `plugin-deprecated` …
=> Exclude plugins without a valid wiki page from the Update Centre JSON files

src/main/resources/wiki-overrides.properties
**Must be merged _after_ PR 20 is merged**
Previously, we couldn't add this override, as the UC generator would crash when dealing with an override URL in this format.
=> Reinstate database-drizzle plugin, now that the UC can handle such URLs

site/generate.sh
This needs to be done whenever a new 1.xxx.1 gets released, as http://updates.jenkins-ci.org/stable/latestCore.txt and in turn the information displayed on the web site depend on it.
=> Add 1.609 UC

src/main/java/org/jvnet/hudson/update_center/Main.java, src/main/java/org/jvnet/hudson/update_center/Plugin.java
Previously, if multiple plugins used the same wiki URL (e.g. workflow-*), then each of those plugins would use the same display name, leading to confusion when users saw multiple plugins with the same title in the Plugin Manager.
Now we use the name defined in the plugin metadata (e.g. POM `<name>`), and fall back to the wiki page title if that metadata is missing.  If the wiki page is missing or failed to be downloaded, we then fall back to using the artifact ID.
=> Use the plugin name from each plugin's metadata, rather than wiki page titles

src/main/resources/artifact-ignores.properties
After discussion with the owner regarding the Jenkins project policy of only hosting open source plugins, they requested removal of this plugin.
They'll create a new, open source plugin at some point in the future.
=> Remove the closed-source Antepedia Reporter plugin.

src/main/resources/artifact-ignores.properties
=> Exclude datadog-build-reporter from Update Center

src/main/resources/wiki-overrides.properties
Followup to the IRC discussion. Just in case. Also sent a heads up to the [current maintainer since last june](https://groups.google.com/forum/#!topic/jenkinsci-dev/mWUgOZc61KY) (@tomasbjerre)
Actually, the 0.7.14 was seemingly borked. It's only present in SCM, but
latest deployed is 0.7.11 on the maven repository...
This reverts commit 0eba8aa485c1cd689d9f1114255c806d564dc637.
=> Revert "Fixed at least since 0.7.14"

site/generate.sh
For example I have some changes prepared for `workflow-plugin` which require baselines after 1.625 (but before 1.642). I think this is the magic incantation.
@reviewbybees
=> Create a 1.642.x-specific site

src/main/resources/wiki-overrides.properties
Its wiki page was renamed without updating the POM and fell victim to [INFRA-301](https://issues.jenkins-ci.org/browse/INFRA-301).
This isn't really the plugin developer's fault, so we can add a temporary override.
Mailing list thread: https://groups.google.com/d/msg/jenkinsci-users/N3D0ceIor5M/PL61zc3IHAAJ
=> Add wiki override for the Play Framework plugin.

src/main/resources/artifact-ignores.properties
As requested on the jenkins-infra mailing list by the plugin author.
`post-mailbox-trigger` was renamed to `post-mailbox-trigger-plugin`.
While the old artifact ID doesn't appear in most Update Centres because it has an invalid wiki URL, it still appears in LTS UCs as the wiki rule is ignored for them.
=> Blacklist poll-mailbox-trigger, due to rename.

src/main/resources/artifact-ignores.properties
As discussed here:
https://issues.jenkins-ci.org/browse/HOSTING-35
Removing the badly named plugin. It has also been released from wrong github repository.
=> Remove octoperf-jenkins-plugin

pom.xml
Note that this PR must **NOT** be merged as-is. It requires changing at least https://ci.jenkins-ci.org/job/Update%20Center/job/infra_update_center_v3/ from JDK7 to JDK8.
Will make doing good changes like https://github.com/jenkinsci/backend-update-center2/pull/44 possible in the future.
As @orrc asked on IRC, do we even have JDK8 available as installable tool on ci.j.o?
Ping @rtyler especially for the tooling part on ci.j.o
Ping also @daniel-beck 
Btw, maybe the next step could/should be creating a `Jenkinsfile` for that build+run, + potentially merging the -mirror downstream job into only one? Can work on that one too if you agree this would be a good thing.
Thanks
=> Update to jdk8

src/main/resources/artifact-ignores.properties
Plugin has now been officially forked under the jenkinsci organization.
Reverts jenkinsci/backend-update-center2#51
See also https://github.com/jenkinsci/backend-update-center2/pull/51#issuecomment-200705467
=> Revert "Hide unknown plugin flyway-runner"

src/main/java/org/jvnet/hudson/update_center/DefaultArtifactTransformationManager.java, src/main/java/org/jvnet/hudson/update_center/HPI.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:S1197 - Array designators "[]" should be on the type, not the variable.
squid:S1845 - Methods and field names should not be the same or differ only by capitalization.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1197
https://dev.eclipse.org/sonar/rules/show/squid:S1845
Please let me know if you have any questions.
Faisal Hameed
=> General code quality fix-2

src/main/resources/artifact-ignores.properties
Source code _appears_ to be here: https://github.com/dsrowell/jsontrigger-jenkins-plugin
But no hosting request (AFAICT), no wiki page, and no fork to jenkinsci, so they should disappear from the update centre.
=> Remove rogue plugin release: jsontrigger.

site/generate.sh
This expects the trusted-ci environment has the necessary key to publish into the update site of course.
References [INFRA-645](https://issues.jenkins-ci.org/browse/INFRA-645)
=> Point the update-center generation at new infrastructure

.gitignore, src/main/resources/artifact-ignores.properties
We are no longer supporting this plugin and it does not work with the current version of the update-sites-manager plugin, so we would like to remove it from the list of available plugins
=> Deprecate blackduck-installer

site/generate.sh
This reverts commit b91db0b39cffbdfde97597d265be6d512c7d7ddc.
As this would not prevent releases from appearing on jenkins.io (it links to the `latest` symlink), let's just not do this.
=> Revert "Don't publish 1.x releases newer than 1.656"

src/main/resources/artifact-ignores.properties
The plugin version was released too soon and we want to remove it for now.
=> Suppress accidental Checkmarx release

src/main/java/org/jvnet/hudson/update_center/DefaultMavenRepositoryBuilder.java, src/main/java/org/jvnet/hudson/update_center/HPI.java, src/main/java/org/jvnet/hudson/update_center/Main.java, src/main/java/org/jvnet/hudson/update_center/MavenRepositoryImpl.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:S1118 - Utility classes should not have public constructors.
squid:MissingDeprecatedCheck - Deprecated elements should have both the annotation and the Javadoc tag.
squid:ClassVariableVisibilityCheck - Class variable fields should not have public accessibility.
squid:AssignmentInSubExpressionCheck - Assignments should not be made from within sub-expressions. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
https://dev.eclipse.org/sonar/rules/show/squid:MissingDeprecatedCheck
https://dev.eclipse.org/sonar/rules/show/squid:ClassVariableVisibilityCheck
https://dev.eclipse.org/sonar/rules/show/squid:AssignmentInSubExpressionCheck
Please let me know if you have …
=> General code quality fix-1

src/main/java/org/jvnet/hudson/update_center/IndexHtmlBuilder.java, src/main/java/org/jvnet/hudson/update_center/LatestLinkBuilder.java, src/main/java/org/jvnet/hudson/update_center/MavenArtifact.java, src/main/java/org/jvnet/hudson/update_center/MavenRepositoryImpl.java, src/main/java/org/jvnet/hudson/update_center/Signer.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1943 - Classes and methods that rely on the default system encoding should not be used. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1943
Please let me know if you have any questions.
Faisal Hameed
=> Code quality fix - Classes and methods that rely on the default system encoding should not be used. 

src/main/resources/wiki-overrides.properties
Required as a workaround for [INFRA-922](https://issues.jenkins-ci.org/browse/INFRA-922).
=> Add wiki override for absint-astree.

site/generate.sh
We don't allow replacing existing releases anyway. Also, skip the time comparison, as its uselessness is the reason we checksummed in the first place.
Further rationale, a recent update center generation build log (excerpt of "milestone" lines):
16:01:10  Started by timer
16:01:17  [INFO] Building Update center generator for jenkins-ci.org 1.21-SNAPSHOT
16:01:30  [INFO] BUILD SUCCESS
16:01:30  + java -jar … -www ./www2/1.554 -cap 1.554.999
16:04:57  + java -jar … -www ./www2/stable-1.554 -cap 1.554.999 -capCore 2.7.999
16:05:19  + java -jar … -www ./www2/1.565 -cap 1.565.999
16:05:39  + java -jar … -www ./www2/stable-1.565 -cap 1.565.999 -capCore 2.7.999
16:05:58  + java -jar … -www ./www2/1.580 -cap 1.580.999
16:06:21  + java -jar … -www ./www2/stable-1.580 -cap 1.580.999 -capCore …
=> Don't checksum plugin releases

site/generate.sh, src/main/java/org/jvnet/hudson/update_center/Main.java
but we have to keep `update-center.json` for JSONP, so JSON version needs another name
=> Somebody pointed out that now we have .json and .js backward

src/main/resources/wiki-overrides.properties
Due to a bug, this plugin is being published to the LTS UC, but because it's
(correctly) not in the regular UC, the .hpi isn't being pushed to the mirrors.
Discussed on IRC with the maintainer.
=> Add temporary wiki override for gerrit-verify-status-reporter.

src/main/resources/wiki-overrides.properties
Maintainer made a new release with the correct wiki URL.
=> Remove now-redundant wiki override for gerrit-verify-status-reporter.

src/main/resources/artifact-ignores.properties
Hi, due to a regression in the plug-in, the Groovy script used for active-choices parameters is not being persisted after saving the job. This can cause users to lose their scripts after installing this version of the plug-in.
Thanks
Bruno
=> Suppress active-choices 1.5 and 1.5.0

src/main/resources/artifact-ignores.properties
Apparently dependent plugins are breaking as this has been released before they were finished being adapted. @rtyler and @i386 are reporting problems in their instances.
@jglick @stephenc
=> Suppress scm-api 2.0 due to dependent plugins breaking

src/main/java/org/jvnet/hudson/update_center/Plugin.java
This reverts commit 1b685b8d7b8d077ff40f943c22a30b0529143aae.
Turns out it wasn't necessary after all, see #92.
=> Revert "Escape plugin title"

src/main/java/org/jvnet/hudson/update_center/Signer.java
Temporary measure to restore update site generation. To be reverted once we have a new cert.
=> [INFRA-1024] Reduce required validity to 15 days

src/main/java/org/jvnet/hudson/update_center/Signer.java
Given that the new certificate was installed, this reverts commit ec77ce018713cb3fe020fbaa929a0f1238feceb3.
=> Revert "[INFRA-1024] Reduce required validity to 15 days"

src/main/resources/artifact-ignores.properties
The basic idea of this is that the upgrades are sufficiently dangerous and *one
direction* (i.e. no rollback except for restoring from a pre-upgrade backup of
JENKINS_HOME) that it's best for Jenkins users to hide these versions until this
is figured out and made more safe.
FYI @michaelneale @vivek  @i386
See https://jenkins.io/blog/2017/01/17/scm-api-2/ for the list of affected
plugins.
=> Ignore SCM API 2.0 related changes until JENKINS-41121 is addressed

src/main/resources/artifact-ignores.properties
Antonio released this, but if you install it, the plugin won't load due to unresolved dependencies.
=> JENKINS-41398 bitbucket-branch-source 2.0.1 is busted

src/main/resources/artifact-ignores.properties
sse-gateway 1.14 has unsatisfied dependency of pubsub-light 1.5. This causes BlueOcean installations to fail.
=> Suppress sse-gateway-1.14 due to unsatisfied dependency

src/main/resources/artifact-ignores.properties
These are the plugins being released over the next 24 hours as a part of the SCM API 2.0 release.
We are proactively suppressing these plugins due to the complexity of this release. Some required dependencies are still blacklisted and some blue ocean parts will be released by that team later in the day. All plugins must be upgraded simultaneously by the user to avoid breaking anything, so contents must appear as simultaneously as possible.
By preemptively blocking these, we can precisely choose the timing of the coordinated release by merging a followup PR which reverts the block.
=> Proactively suppress SCM API 2.0 and downstream

src/main/resources/artifact-ignores.properties
ruby-runtime 0.13 is broken and there seems to be no maintainer to fix it. See [JENKINS-37353](https://issues.jenkins-ci.org/browse/JENKINS-37353), [JENKINS-37771](https://issues.jenkins-ci.org/browse/JENKINS-37771) and [JENKINS-38145](https://issues.jenkins-ci.org/browse/JENKINS-38145).
According to the [metadata](https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/General/releases/org/jenkins-ci/plugins/ruby-runtime/0.13/ruby-runtime-0.13.hpi) in Artifactory, 0.13 has been deployed by @eitoball. I tried to [ping](https://issues.jenkins-ci.org/browse/JENKINS-37353?focusedCommentId=282631&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-282631) him through JIRA a few days ago, but got no response.
Downgrading to 0.12 fixes the problems, so removing 0.13 …
=> do not distribute ruby-runtime 0.13

src/main/resources/artifact-ignores.properties
Additions from `plugin-deprecated` label in an effort to start relying less on the wiki for building the update site.
https://wiki.jenkins-ci.org/labels/viewlabel.action?ids=46727211&key=JENKINS&startIndex=0
@orrc @rtyler @batmat
=> Ignores additions from wiki

src/main/resources/artifact-ignores.properties
- assembla-oauth: Missed it because wiki page has no useful info
- buildheroes: wiki macro had wrong ID
- ion-deployer-plugin: I misread the wiki macro
Followup to https://github.com/jenkinsci/backend-update-center2/pull/111
CC @orrc @rtyler @batmat
=> Add/fix the last few wiki-blacklisted plugins

site/generate.sh
https://updates.jenkins-ci.org/current/plugin-documentation-urls.json exists.
https://updates.jenkins-ci.org/plugin-documentation-urls.json does not.
This fixes that.
=> Symlink the mapping file to the top level directory

src/main/java/org/jvnet/hudson/update_center/Main.java
Will need a corresponding change downstream to link to the plugins site instead of the wiki: https://github.com/jenkins-infra/jenkins.io/pull/736
I added this as a new element as I don't know who might be using this.
=> Reference plugins.jenkins.io on release history

Jenkinsfile
UNTESTED
Assumes https://github.com/jenkins-infra/backend-update-center2/pull/120 merged.
@rtyler WDYT? Or is the disk space requirement for the local Maven repo making this useless? Note that https://github.com/jenkins-infra/backend-update-center2/pull/115 could improve the situation.
Worst case we'll just build the generator, but not run it, in PRs.
=> Add Jenkinsfile for PR builds

pom.xml, src/test/java/org/jvnet/hudson/update_center/WarningsTest.java
This ensures that all patterns for plugins match at least one release.
A complete list of matched versions will be written to `target/surefire-reports/org.jvnet.hudson.update_center.WarningsTest-output.txt` for inspection.
=> Test warning patterns against release history

src/main/java/org/jvnet/hudson/update_center/Plugin.java
`ZipEntry#getTime()` uses the default TZ to convert the zip date to a unix epoch:
https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipEntry.html#getTime--
>If the entry is read from a ZIP file or ZIP file formatted input stream, this is the last modification time from the date and time fields of the zip file entry. The default TimeZone is used to convert the standard MS-DOS formatted date and time to the epoch time.
So to have a consistent time stamp in the output independent of the current system TZ, we should not set a time zone for the date formatter.
=> Make timestamps in output TZ independent

src/main/java/org/jvnet/hudson/update_center/Main.java, src/main/java/org/jvnet/hudson/update_center/Plugin.java, src/main/java/org/jvnet/hudson/update_center/VersionCappedMavenRepository.java
I noticed extreme amounts of traffic when building an update site locally, even with the minimal possible output (`-skip-release-history` set, `-www-download` or `-download` not set).
Sure, there's `-maxPlugins`, but I wanted the full output.
Turns out the update center build…
- downloads all plugin HPIs to compare to the version cap, even if that is undefined (i.e. `999.999`).
- downloads all plugin HPIs to find the two with the newest versions for further use.
Both are unnecessary, and optimizing them away result in a good reduction in traffic and disk space use in the local Maven repository if `-cap` isn't set.
Also remove a check nobody cares about related to when an artifact was created -- there's maintenance/stable branches, so that check seems invalid even if anyone cared.
=> Optimize execution

src/test/java/org/jvnet/hudson/update_center/WarningsTest.java
This extends `target/surefire-reports/org.jvnet.hudson.update_center.WarningsTest-output.txt` with a list of plugin versions that don't match a certain version. This will make it easier to confirm that we actually match everything we intended to match (it's typically a shorter list than versions that match).
=> Add log message when a warning does not apply to a plugin version

src/main/resources/artifact-ignores.properties
Duplicate plugin brought into the UC after the wiki page requirement was dropped; artifact ID was changed after version 1.0.0: https://github.com/jenkinsci/delphix-plugin/commit/d80a744d8f6e2d8edf3f9a3f2e5009bf34455ca0
=> Exclude renamed delphix-plugin.

src/main/java/org/jvnet/hudson/update_center/Plugin.java
**Do not merge** before people had some time to speak up and point us to consumers of the `scm` entry in the `update-center.json`, and we've adapted https://github.com/jenkins-infra/backend-jenkins-plugin-info-plugin to handle the new format.
Context:
https://issues.jenkins-ci.org/browse/WEBSITE-332
http://lists.jenkins-ci.org/pipermail/jenkins-infra/2017-March/001058.html
This tries to determine the SCM URL from the POM or parent POM's `scm/url` or `scm/developerConnection` elements. URLs pointing to old SVN repos are discarded, GitHub.com/jenkinsci URLs are rewritten to https:// (especially if SSH connection strings).
1100+ plugins have SCM URLs after this change (untested, some may be wrong), ~100 cannot be determined or only have known obsolete URLs, and another ~110 have URLs outside …
=> [WEBSITE-332] Replace 'scm' host name by full browsable jenkinsci GitHub URL

site/generate.sh
@olivergondza @rtyler @orrc @batmat @oleg-nenashev
Per https://github.com/jenkins-infra/backend-update-center2/pull/114#issuecomment-283852491:
> We should probably consider removing the update sites predating 2.0. It'll be a year (which is what we originally started with in dd88dc7 -- and 2d67efa rotated out the oldest one).
> 
> Then I took over, and just didn't bother doing that for reasons now unknown to me…
Oliver would like to keep 1.609 around for a while longer, so accommodate that.
Related: Release dates via http://jenkins-ci.org/changelog-stable
* *1.554.3 (2014/06/30)*
* *1.565.3 (2014/10/01)*
* *1.580.3 (2015/01/27)*
* *1.596.3 (2015/05/20)*
* 1.609.3 (2015/09/02)
* 1.625.3 (2015/12/09)
* 1.642.4 (2016/03/31)
* 1.651.3 (2016/06/08)
* 2.7.4 (2016-09-08)
=> Remove ancient baselines

src/main/resources/artifact-ignores.properties, src/main/resources/warnings.json
The permissions issue has been resolved in 1.0.2, but issue a new
warning for the Administer/Run Scripts issue that's still present.
---
CC @justice3120 Sorry for the delay.
=> Restore distribution of app-detector

src/main/resources/artifact-ignores.properties
With BuildGraph-View-1.6 version dependency with Build-Flow-Plugin marked as optional.
Now with latest version there is no mandate dependency,
@daniel-beck 
Let me know whether this suffix to restore the plugin.
Thanks
=> Restore BuildGraph-View Plugin

pom.xml
This is a dependency for https://github.com/jenkins-infra/backend-extension-indexer so we may need a proper release some time soon to fix the extension indexer.
=> Upgrade to 2.0 after major changes

Jenkinsfile, pom.xml, site/generate.sh, src/main/java/org/jvnet/hudson/update_center/Main.java, src/main/java/org/jvnet/hudson/update_center/StableMavenRepository.java
Prevents serving regular weeklies to LTS users like earlier today due to premature merge of https://github.com/jenkins-infra/backend-update-center2/pull/144
Preparation for https://issues.jenkins-ci.org/browse/INFRA-1193
@olivergondza  @rtyler
=> Add option to filter for stable core releases

src/main/resources/artifact-ignores.properties, src/main/resources/warnings.json
https://github.com/jenkinsci/splunk-devops-plugin/commit/8a845a79031af6ed8c4cc25db399363f9c34188d\#diff-d0d9c36aca7861d4559fd59371c1c95b, the step will throw UnsupportedOperationException
=> fixed SECURITY-496, SplunkMessageStep was disabled in 1.4.3

src/main/resources/artifact-ignores.properties
https://issues.jenkins-ci.org/browse/JENKINS-45126
Something went wrong with the 1.27 release.
CC @wolfs
=> [JENKINS-45126] Remove Gradle plugin 1.27

src/main/resources/artifact-ignores.properties
This service appears to have been shut down:
https://wiki.jenkins.io/display/JENKINS/Mber+Plugin
CC @firepub-pfreeman @onefrankguy
=> Remove mber plugin from distribution

src/main/resources/artifact-ignores.properties
cc @vivek @i386
What happened was a partial deploy - it failed during a release:perform in maven due to a full disk (no warning) - leaving it in a bad state. 1.1.4 will go out to replace it, but we don't know of another way to undo the damage
=> A bad deploy is bad

src/main/java/org/jvnet/hudson/update_center/Main.java
Output before:
java.io.IOException: ln failed
at org.jvnet.hudson.update_center.Main.stage(Main.java:382)
at org.jvnet.hudson.update_center.Main.buildPlugins(Main.java:326)
at org.jvnet.hudson.update_center.Main.buildUpdateCenterJson(Main.java:248)
at org.jvnet.hudson.update_center.Main.run(Main.java:198)
at org.jvnet.hudson.update_center.Main.run(Main.java:168)
at org.jvnet.hudson.update_center.Main.main(Main.java:155)
Output now:
Exception in thread "main" java.io.IOException: 'ln -f /Users/danielbeck/.m2/repository/org/jenkins-ci/main/jenkins-war/2.68/jenkins-war-2.68.war /Users/danielbeck/Repositories/jenkins-infra/backend-update-center2.git/./download/war/2.68/jenkins.war' failed with code 1
Error: ln: illegal option -- b
usage: ln [-Ffhinsv] source_file [target_file]
ln [-Ffhinsv] …
=> [INFRA-1266] Better ln logging

src/main/resources/artifact-ignores.properties
https://github.com/jenkinsci/kubernetes-pipeline-plugin/pull/31 is a serious problem for anyone who has that plugin installed.
Unless Jenkins is configured with an HTTPS URL (which bypasses the mirror network), the redirect of the general update site URL to one of the mirrors will not work. Jenkins instances configured this way will neither receive update notifications, nor security warnings, unless that happens before the redirects are disabled. Especially for instances not restarting regularly, that's a major problem.
For an example, see recent comments to [JENKINS-38185](https://issues.jenkins-ci.org/browse/JENKINS-38185) from an affected user.
Therefore I propose to blacklist the affected release of the plugin (https://github.com/jenkinsci/kubernetes-pipeline-plugin/commit/d8940011fc93 …
=> Ignore kubernetes-pipeline plugins 1.3

src/main/resources/artifact-ignores.properties
https://issues.jenkins-ci.org/browse/JENKINS-46130
Maintainers are not re-releasing a completely broken 1.0.4, so it's time this is blacklisted. I expected that to just be fixed and the world to move on, but more than three weeks later, it's not.
Apparent maintainers: @tommysdk @Crasher-ua
@oleg-nenashev @rtyler @orrc @batmat
=> [JENKINS-46130] Remove delivery-pipeline-plugin-1.0.4

src/main/resources/artifact-ignores.properties
Downstream from https://github.com/jenkins-infra/repository-permissions-updater/pull/459 and https://github.com/jenkins-infra/repository-permissions-updater/pull/463 
@stephenc discovered a naming rule shortly after people started creating plugins it applies to. It was too late for @samrocketman's first release.
CC @slide and @orrc perhaps you could look out for these in HOSTING?
=> scm-branch-pr-filter was renamed to scm-filter-branch-pr

site/generate.sh
I'm sick of waiting 40 minutes for this build to finish every time I release security updates.
Supporting ten release lines via the update sites is beyond ridiculous, nobody should be using Jenkins this old. Anything older than 2.46.2 is plain insane, so I'm being generous here: Four lines means an update once a year. That seems reasonable.
=> Limit supported releases from 10 to 7

src/main/resources/artifact-ignores.properties
This closed-source plugin was accidentally uploaded and needs to be removed from UC.
Also see https://github.com/jenkins-infra/repository-permissions-updater/pull/506
=> remove loadrunner from uc

site/generate.sh
Followup to https://github.com/jenkins-infra/backend-update-center2/pull/168 based on the consensus reached there of going with five supported baselines starting with 2.89.x.
Today, we update sites for 2.73, 2.60, 2.46, 2.32, 2.19, 2.7, and 1.651.
Tomorrow, we will add 2.89, and rotate out 2.19, 2.7, and 1.651.
=> Limit to five release lines

src/main/resources/warnings.json
Prevent apparent redundancy when running an older core release, like this:
> ![screen shot](https://user-images.githubusercontent.com/1831569/33673605-8977970a-daad-11e7-90fa-030fd31d0ea2.png)
=> Be more specific about 'multiple vulnerabilities' messages

src/main/resources/warnings.json
I cannot close SECURITY-296 as I cannot see it myself. (I used JENKINS-43811 for that)
I edited https://wiki.jenkins.io/display/JENKINS/Script+Security+Support+in+Plugins with the information needed.
Please tell me if I need to do other things.
=> update claim plugin vulnerable version

src/main/resources/artifact-ignores.properties
I should have been done this few years ago when I did [this change](https://github.com/jenkinsci/cloudbees-disk-usage-simple-plugin/commit/8857d66b83aceb0cccfd8a10878db58d427eeb72).
=> Ignoring a plugin because it was renamed (artifactId)

src/main/resources/artifact-ignores.properties, src/main/resources/warnings.json
Restore Artifact Deployer plugin distribution for version 1.2 or higher
=> [SECURITY-294] Restore Artifact Deployer plugin distribution 

src/main/java/org/jvnet/hudson/update_center/AlphaBetaOnlyRepository.java
Basically revert https://github.com/jenkins-infra/backend-update-center2/commit/0152b87eb88a4acb0a4bd0b4e498be643923365e
Blocks (sort of) https://github.com/jenkins-infra/jenkins.io/pull/1335
`BlazeMeterJenkinsPlugin` and `deployit-plugin` have long been released, only `heroku-jenkins-plugin` will be removed by this unless/until it gets a proper release.
TBH, given https://plugins.jenkins.io/heroku-jenkins-plugin stats (~130 installs, no release since 2012) and https://github.com/heroku/heroku-jenkins-plugin/commit/348e94b6932eae7da5e73615d9f6130f171311ae (deprecated two years ago), this doesn't look like something we need to keep a workaround for indefinitely.
Pinging @ryanbrainard the last known maintainer to give a chance to respond (or just release a non-beta version of the plugin).
=> [INFRA-1482] Drop support for historically beta-only plugins

src/main/resources/artifact-ignores.properties
[JENKINS-49323](https://issues.jenkins-ci.org/browse/JENKINS-49323)
CloudBees is ending the CloudBees Jenkins Advisor service.  We need to remove the plugin from the update center.  Current users will be notified about the service ending.
=> [JENKINS-49323] Add cloudbees-jenkins-advisor to the blacklist

src/main/resources/artifact-ignores.properties
blacklist qtest plugin v1.2.0 because it's draft release and not the latest release
=> blacklist qtest plugin v1.2.0 because it's draft release

pom.xml, src/main/java/org/jvnet/hudson/update_center/Plugin.java, src/test/java/org/jvnet/hudson/update_center/PluginTest.java
'Hudson', 'Jenkins', and 'Plugin' (or 'Plug-In') is redundant, so
remove them.
@slide @batmat @orrc WDYT?
=> Simplify plugin display names

src/main/resources/warnings.json
@Wadeck discovered that it's not possible to hide core warnings in the security configuration, as the form submission only submits the part after the period, e.g. the XML file will contain
<string>107</string>
instead of 
<string>core-2.107</string>
Work around this issue by using underscores instead. Since apparently nobody can have hidden these warnings interactively, it shouldn't be a big deal to change their IDs. Only those who hide them programmatically will get them again. I don't expect too many people will be affected by this change.
=> Use underscores instead of period because of a core problem

src/main/resources/artifact-ignores.properties
Suspend distribution of plugins with mandatory dependencies on [plugins that have been removed from distribution in the 2018-03-26 security advisory](https://jenkins.io/security/advisory/2018-03-26/), and therefore can no longer be installed.
Thanks to @oleg-nenashev for letting me know about this problem.
FYI @PikeTec  @LaisvydasLT @AMCBridgeDevTeam and @roman-bilyi
=> Add plugins dependent on delisted plugins

src/main/java/org/jvnet/hudson/update_center/MavenArtifact.java
Followup to #191 that hopefully is less bandwidth hungry:
- Skip SHA-256 which was mostly for convenience (compare to Artifactory checksums) anyway
- Use base64 encoding for SHA-512 to shave off bits at the cost of being weird
FYI @orrc (previous #191 reviewer), @rtyler
=> Don't record SHA-256, use base64 for SHA-512

src/main/resources/artifact-ignores.properties
We consider credentials stored in plaintext to be vulnerabilities, and the maintainer ignored my requests to fix this before initial release:
https://issues.jenkins-ci.org/browse/HOSTING-568?focusedCommentId=339941&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-339941
https://github.com/jenkins-infra/repository-permissions-updater/pull/721#issuecomment-396358858
So suspend distribution while the plugin has no users, and the issue is unresolved.
=> Blacklist influxdb-query for initial release with vulnerability

pom.xml, src/main/java/org/jvnet/hudson/update_center/MavenArtifact.java, src/main/java/org/jvnet/hudson/update_center/MavenRepositoryImpl.java, src/main/java/org/jvnet/hudson/update_center/Plugin.java
[INFRA-1666](https://issues.jenkins-ci.org/browse/INFRA-1666)
See [installed view](https://github.com/jenkinsci/jenkins/blob/6c49fabc45062e86f6243225a4c6c6a929725fc0/core/src/main/resources/hudson/PluginManager/installed.jelly#L87-L100) vs. [update view](https://github.com/jenkinsci/jenkins/blob/6c49fabc45062e86f6243225a4c6c6a929725fc0/core/src/main/resources/hudson/PluginManager/table.jelly#L100-L102).
Before, from [this](https://github.com/jenkinsci/accurev-plugin/blob/b2a01a82c982f61bc50e96af548e339f9c29ff61/pom.xml#L15):
```json
"excerpt": "This plugin allows you to use AccuRev as a SCM.",
```
After, from [this](https://github.com/jenkinsci/accurev-plugin/blob/b2a01a82c982f61bc50e96af548e339f9c29ff61/src/main/resources/index.jelly#L3):
```json
"excerpt": "This plugin integrates <a …
```
=>  [INFRA-1666] Prefer index.jelly to <description> for excerpt

site/generate.sh
While we figure out the performance issues, return to not generating this file that requires checksumming all past plugin releases and increases run time from 20 minutes to ~70 minutes.
=> Do not generate plugin-versions.json file for now

pom.xml, src/main/java/org/jvnet/hudson/update_center/GitHubSource.java, src/main/java/org/jvnet/hudson/update_center/Plugin.java
Both finds more repos, and is quicker overall.
Newly discovered repos via fallback:
* jenkinsci/accelerated-build-now-plugin
* jenkinsci/aws-beanstalk-publisher-plugin
* jenkinsci/awseb-deployment-plugin
* jenkinsci/clearcase-ucm-plugin
* jenkinsci/codeclimate-plugin
* jenkinsci/commit-message-trigger-plugin
* jenkinsci/copy-data-to-workspace-plugin
* jenkinsci/drmemory-plugin
* jenkinsci/dumpinfo-buildwrapper-plugin
* jenkinsci/flashlog-plugin
* jenkinsci/gearman-plugin
* jenkinsci/jquery-detached
* jenkinsci/rqm-plugin
* jenkinsci/scripted-cloud-plugin
=> Improve GitHub repo detection using GitHub API

site/generate.sh
Right now, `stable/` is a symlink to `stable-` ☹️ 
This script is lacking `set -o nounset`
=> Fix symlink to stable

src/main/java/org/jvnet/hudson/update_center/Plugin.java
Probably a side effect of recent changes is that this is now typically an empty string, rather than null. I'm not sure why, but given the surprising number of plugins with undefined title, this needs to be fixed quickly.
"title": "accelerated-build-now-plugin",
"title": "anything-goes-formatter",
"title": "artifact-promotion",
"title": "beer",
"title": "behave-testresults-publisher",
"title": "build-env-propagator",
"title": "build-metrics",
"title": "build-name-setter",
"title": "buildgraph-view",
"title": "built-on-column",
"title": "categorized-view",
"title": "change-assembly-version-plugin",
"title": "chef-tracking",
"title": "chosen-views-tabbar",
"title": "chromedriver",
"title": "couchdb-statistics",
"title": "countjobs-viewstabbar",
"title": "crittercism-dsym",
"title": …
=> Fall back to artifactId when title is empty string

Jenkinsfile, site/generate.sh, site/publish.sh, src/main/java/org/jvnet/hudson/update_center/ArtifactoryRedirector.java, src/main/java/org/jvnet/hudson/update_center/Main.java
Sample output (excerpt):
~~~~
RewriteEngine on
RewriteRule ^plugins/AnchorChain/1.0/AnchorChain.hpi$ http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/AnchorChain/1.0/AnchorChain-1.0.hpi [NC,L,R]
RewriteRule ^plugins/ApicaLoadtest/1.0/ApicaLoadtest.hpi$ http://repo.jenkins-ci.org/releases/com/apica/ApicaLoadtest/1.0/ApicaLoadtest-1.0.hpi [NC,L,R]
RewriteRule ^plugins/ApicaLoadtest/1.1/ApicaLoadtest.hpi$ http://repo.jenkins-ci.org/releases/com/apica/ApicaLoadtest/1.1/ApicaLoadtest-1.1.hpi [NC,L,R]
RewriteRule ^plugins/ApicaLoadtest/1.10/ApicaLoadtest.hpi$ http://repo.jenkins-ci.org/releases/com/apica/ApicaLoadtest/1.10/ApicaLoadtest-1.10.hpi [NC,L,R]
RewriteRule ^plugins/ApicaLoadtest/1.4/ApicaLoadtest.hpi$ http://repo.jenkins-ci.org/releases/com/apica/ApicaLoadtest/1.4/ApicaLoadte …
=> Add generation of htaccess file for fallback redirects

src/main/resources/artifact-ignores.properties
This breaks too badly - see
https://issues.jenkins-ci.org/browse/JENKINS-53399. I just helped
someone deal with the result of upgrading from 2.18 to 3.0 - folder
shared libraries and permissions all broke horribly, and were fixed
with a downgrade.
=> [JENKINS-53399] Blacklist config-file-provider 3.0

src/main/resources/artifact-ignores.properties
The first actual release of `sge-cloud-plugin` was performed this week.
Unfortunately, it has a mandatory dependency on [the copy-to-slave plugin we blacklisted in March](https://jenkins.io/security/advisory/2018-03-26/#SECURITY-545), so it cannot actually be installed. Additionally, Jenkins instances will show this warning, even if they have neither mentioned plugin installed:
WARNING: Could not find dependency copy-to-slave of sge-cloud-plugin
Suspending distribution until this dependency is removed or made optional.
FYI @jmcgeheeiv
=> Suspend distribution of sge-cloud-plugin

src/main/resources/label-definitions.properties
Pull request should be self-explanatory. 
I'm the plugin maintainer, have commit access for the repository and can publish releases if that matters.
Plugin repository: https://github.com/jenkinsci/calendar-view-plugin
=> Add ui label for calendar-view plugin

src/main/resources/artifact-ignores.properties
Pending investigation whether https://github.com/jenkinsci/workflow-api-plugin/pull/81 or something else helps users. CC @svanoort @dwnusbaum; [release notes](https://wiki.jenkins.io/display/JENKINS/Pipeline+Job+Plugin)
=> [JENKINS-54073] Suppress workflow-job 2.26 for now

src/main/resources/artifact-ignores.properties
With version 3.0-alpha (Oct. 10, 2018) - scriptler has fixed all its security vulnerabilities.
=> remove scriptler from list of ignored plugins

src/main/java/org/jvnet/hudson/update_center/MavenRepositoryImpl.java
=> Make resolution robust against URL problems

src/main/resources/artifact-ignores.properties
As mentioned by @daniel-beck in jenkins-infra/repository-permissions-updater#943, filling this PR to ignore `binary-deployer`. The project was / is a POC and not meant to be deployed. It's not hosted in `jenkinsci` org either.
=> Ignore binary-deployer as deployed by mistake

src/main/resources/artifact-ignores.properties
As requested by @markewaite
The expectation was to land these releases into the experimental UC only.
=> Hide git-client 3.0.0-rc and git 4.0.0-rc

src/test/java/org/jvnet/hudson/update_center/WarningsTest.java
@Wadeck Due to consistent URLs, this will allow ASCII-sorting latest warnings to the end in the `WarningsTest-output.txt`
=> Change WarningsTest output format

src/main/resources/artifact-ignores.properties
We would like to remove or deprecate the old Fortify360 plugin. It's obsolete and has not worked for years. It's been completely replaced with the Fortify plugin that's been open sourced a few days ago [https://github.com/jenkinsci/fortify-plugin](https://github.com/jenkinsci/fortify-plugin)
Fortify360 is the name that's not used by our product management anymore, and having this plugin could be very confusing for our customers. The new plugin's wiki is here [https://wiki.jenkins.io/display/JENKINS/Fortify+Plugin](https://wiki.jenkins.io/display/JENKINS/Fortify+Plugin)
Also, here's the relevant JIRA ticket with more details: [HOSTING-710](https://issues.jenkins-ci.org/browse/HOSTING-710)
=> Remove the obsolete fortify360 plugin

src/main/resources/artifact-ignores.properties
The name of the plugin "hp-application-automation-tools-plugin" should be written as in the following link?
[repo.jenkins-ci.org](https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/hp-application-automation-tools-plugin/)
Also indented the comments after #.
Let me know if any changes are required.
=> [JENKINS-55159] Add hpaat plugin 5.6 to the blacklist

src/main/resources/artifact-ignores.properties
Please ignore configuration-as-code 1.9 plugin from update center :sweat:
=> ignore JCasC 1.9, failed shading of snakeyaml

src/main/resources/warnings.json
https://github.com/jenkinsci/deployhub-plugin/releases/tag/deployhub-8.0.14 has a fix at https://github.com/jenkinsci/deployhub-plugin/commit/6ad56362087f6d34c3532a0962a881cd8a822394
@sbtaylor15 FYI this will disable the security warning in Jenkins when 8.0.14 is installed, and on the plugin site (https://plugins.jenkins.io/deployhub).
I'd also like to understand what went wrong in notifying you before release, if you're willing to help me with that.
=> Adapt warning for deployhub release with fix

src/main/resources/warnings.json
Update/remove warnings about aqua-security-scanner from https://plugins.jenkins.io/aqua-security-scanner and update center metadata because https://github.com/jenkinsci/aqua-security-scanner-plugin/commit/6468cec53cc4ad32d79aa016631ba441bbf07b4a appears to have fixed the issue in 3.0.16.
FYI @oranmoshai
=> Adapt warning for aqua-security-scanner-3.0.16

src/main/resources/warnings.json
@stolp FYI
**Not to be merged before 2.1.0 or later is released**
=> Disable security warning for klaros-testmanagement-2.1.0

src/main/resources/artifact-ignores.properties
Referencing https://github.com/jenkinsci/google-compute-engine-plugin/issues/85 for the Google compute engine plugin for jenkins: https://github.com/jenkinsci/google-compute-engine-plugin
Regression detected.
There was a bug in which the instance ID for the virtual machine cloud was not being set. Agents could not be launched as a result.
Bug has since been patched (3.1.1). Would like to remove buggy release (3.1.0).
=> Remove bad release for google-compute-engine

src/main/resources/artifact-ignores.properties
Issue https://github.com/jenkinsci/build-name-setter-plugin/issues/39
Release 2.0.0 should not be available to download any more as it is probably broken
=> Changes release availability of build-name-setter-plugin

src/main/resources/warnings.json
Test output:
```
Warning https://jenkins.io/security/advisory/2019-05-31/#SECURITY-1015%20(1) / SECURITY-1015-1 does NOT match org.jenkins-ci.plugins:artifactory:3.2.3
Warning https://jenkins.io/security/advisory/2019-05-31/#SECURITY-1015%20(1) / SECURITY-1015-1 does NOT match org.jenkins-ci.plugins:artifactory:3.2.4
Warning https://jenkins.io/security/advisory/2019-05-31/#SECURITY-1015%20(2) / SECURITY-1015-2 does NOT match org.jenkins-ci.plugins:artifactory:3.2.4
Warning https://jenkins.io/security/advisory/2019-05-31/#SECURITY-1347 / SECURITY-1347 does NOT match org.jenkins-ci.plugins:artifactory:3.2.3
Warning https://jenkins.io/security/advisory/2019-05-31/#SECURITY-1347 / SECURITY-1347 does NOT match org.jenkins-ci.plugins:artifactory:3.2.4
```
_SECURITY-1015 (2)_ took one release …
=> Update warnings after fixes in Artifactory Plugin 3.2.3 and 3.2.4

src/main/resources/artifact-ignores.properties, src/main/resources/label-definitions.properties
Testing out https://github.com/jenkinsci/jenkins/pull/4073 :sweat_smile:
=> mark configuration-as-code-support with deprecation label

src/main/resources/artifact-ignores.properties
I had a mistake when releasing plugin version 1.4.2 and want to add qtest jenkins plugin version 1.4.1 to blacklist release.
=> add qtest jenkins plugin version 1.4.1 to blacklist release

src/main/resources/artifact-ignores.properties
Replaced by [google-compute-engine-3.3.2](https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/General/releases/org/jenkins-ci/plugins/google-compute-engine/3.3.2).
=> Remove google-compute-engine-3.3.1 after failed deployment

src/main/resources/artifact-ignores.properties
XLTest Plugin was renamed in https://github.com/jenkinsci/xltestview-plugin/commit/ea034f9929b520e63b9ce15aed9bdb62354146cf by @amolenaar with the now obsolete plugin never having been removed from distribution. Confusingly, versioning restarted, XL Test 1.1.0 was released in May 2015, XL TestView 1.0.0 was released in June 2015.
Clang Scan-Build appears to have been accidentally renamed, since @rodrigc did not mention anything about that in https://github.com/jenkinsci/clang-scanbuild-plugin/commit/a6d57b67f6fbd0a9893ecf6436c54ecb670d5829 and the [wiki page](https://wiki.jenkins.io/display/JENKINS/Clang+Scan-Build+Plugin) plugin macro continues to reference the now obsolete artifact ID.
=> Blacklist renamed clang-scanbuild-plugin and xltest-plugin

site/generate-htaccess.sh, site/test/redirects.sh
Redirect issues with
* update-center.actual.json, 
* latestCore.txt, and 
* plugin-documentation-urls.json
Tests have been improved to show the issue and avoid any later regression
=> [INFRA-2151] Fixed redirect issues with some files

site/generate-htaccess.sh, site/test/redirects.sh
https://github.com/jenkins-infra/update-center2/pull/281 resulted in wrong redirects. This change aims to fix that.
Also don't make the test script silently die on `curl` failure.
=> Fix redirects

src/main/resources/artifact-ignores.properties, src/main/resources/label-definitions.properties
the service has been shut down and replaced with an alternate system.
following instructions from here
https://jenkins.io/doc/developer/publishing/removing-from-distribution/
please indicate if additional steps required
=> Remove codescan - 

src/main/resources/label-definitions.properties
I am the [AppCenter plugin](https://plugins.jenkins.io/appcenter) maintainer and would like to add the plugin as well as the following labels: `upload` `android` `ios`
=> Add appcenter plugin and labels

src/main/resources/artifact-ignores.properties
Per the comment in the file, the veracode-scanner open source plugin is not actively maintained and will cease working later this month when Veracode updates its authentication method. Users should migrate to the supported Veracode Jenkins plugin available directly from [help.veracode.com](https://help.veracode.com/reader/PgbNZUD7j8aY7iG~hQZWxQ/yQtYXnlbLA6wsWodLn5zdw).
=> Remove veracode-scanner

src/main/resources/artifact-ignores.properties
Durable task 1.31 introduced a Go binary as an alternative to the existing shell wrapper for some platforms to try to solve some robustness issues with the existing wrapper. Unfortunately, the binary has some issue in various environments, and the detection logic for when the binary should be used instead of the shell wrapper needs to handle some additional cases. 
See [JENKINS-59903](https://issues.jenkins-ci.org/browse/JENKINS-59903) and [JENKINS-59907](https://issues.jenkins-ci.org/browse/JENKINS-59907). There is a system property to disable the new behavior, but we want to stop distributing the new version for now while we work on a fix.
CC @car-roll
=> Suspend durable-task 1.31 from distribution

src/main/resources/artifact-ignores.properties
Incompatibilities in this version:
* awaitility dependency was changed to a test scope, but should not have been.
* jclouds referencing BaseEncoding.base64() which is not available to the version of guava that Jenkins uses.
=> Remove google-compute-engine-plugin 4.1.0 from distribution

src/main/resources/artifact-ignores.properties
Service has been discontinued. https://www.hockeyapp.net/blog/2019/11/16/hockeyApp-is-being-retired.html
Users are advised to migrate to the Jenkins AppCenter plugin instead.
=> Hide updates for HockeyApp

src/main/resources/warnings.json
New release out of alpha: https://github.com/jenkinsci/scriptler-plugin/releases/tag/scriptler-3.1
The vulnerabilities were announced in https://jenkins.io/security/advisory/2017-04-10 but they are all corrected now:
✔️ JENKINS-21327 + JENKINS-21336 + SECURITY-367 => https://github.com/jenkinsci/scriptler-plugin/pull/32
✔️ SECURITY-333 => https://github.com/jenkinsci/scriptler-plugin/commit/7873bee3d03ee669d67738feefa347fbe003c5fc
✔️ SECURITY-334 => https://github.com/jenkinsci/scriptler-plugin/pull/34
✔️ SECURITY-365 + SECURITY-366 + SECURITY-678 => https://github.com/jenkinsci/scriptler-plugin/commit/0db5380fe2aea39657f96e27a5ccca79e706e716
✔️ SECURITY-691 => https://github.com/jenkinsci/scriptler-plugin/commit/57567d8944dd255adfdd1d0cd45d85eecc8432e5
@daniel-beck 
@imod
=> Remove warnings for scriptler

src/main/java/org/jvnet/hudson/update_center/Plugin.java
[INFRA-2292](https://issues.jenkins-ci.org/browse/INFRA-2292)
**Untested**. Do we need to just run CI on it and manually verify?
@oleg-nenashev
=> [INFRA-2292] Read Url from the plugin manifest before looking for pom.xml#/project/url

src/main/resources/warnings.json
I'm currently working on improving the tooling used by the Jenkins security team.
One of the side effects is that we will no longer update this file manually, but use scripts that add or update entries in this file. To get started, sort all existing entries.
This change:
* Reformats the file, removing empty lines and such (https://github.com/jenkins-infra/update-center2/commit/f866d41d29ec2761e051fcee192cdb5e79aba952)
* Fixes a duplicate ID (https://github.com/jenkins-infra/update-center2/commit/d94c2dbf2f785a55aedacdbd0ba7619be39291bb)
* Applies `jq 'unique_by(.id) | sort_by(.url)'`. While this uniquifies, since it's the same number of lines added/removed in https://github.com/jenkins-infra/update-center2/commit/6a6741742f6edd84215e8ee74b1d19360c2ffc65, nothing was actually removed.
---- …
=> Reformat warnings.json

src/main/resources/warnings.json
[SECURITY-957](https://jenkins.io/security/advisory/2019-04-03/#SECURITY-957) was corrected in https://github.com/OctopusDeploy/octopus-jenkins-plugin/commit/c087af46b69f32ce8ceeb0bd7a0216f1cb5af577
✔️ Tested manually
@daniel-beck 
@hnrkndrssn (author of the correcting commit)
@tothegills (approver of the correcting commit + requester of this removal)
⚠️ Be careful, the code is not up-to-date between [jenkinsci](https://github.com/jenkinsci/octopusdeploy-plugin) fork and the [original repo](https://github.com/OctopusDeploy/octopus-jenkins-plugin)
=> Remove warning for octopusdeploy

src/main/resources/warnings.json
SECURITY-795 => https://github.com/jenkinsci/gitlab-oauth-plugin/pull/16
SECURITY-796 => https://github.com/jenkinsci/gitlab-oauth-plugin/pull/17
both included in the last release: https://github.com/jenkinsci/gitlab-oauth-plugin/releases/tag/gitlab-oauth-1.5
@daniel-beck
=> Remove warnings for gitlab-oauth

src/main/resources/warnings.json
Limit security warning to [0.1,0.13.*], 0.14 released with fix:
https://github.com/jenkinsci/depgraph-view-plugin/pull/18
Advisory: 
https://jenkins.io/security/advisory/2019-07-11/#SECURITY-1177
=> [SECURITY-1177] Limit affected versions

src/main/resources/wiki-overrides.properties
The GitHub readme for these plugins contains a reasonable explanation, OTOH the Wiki page extraction for them is quite unstable so e.g. https://plugins.jenkins.io/pmd/ shows just a link to the wiki and that redirects back to plugins.jenkins.io.
I hope this is compatible with the current improvements of deprecation warnings.
CC @uhafner @daniel-beck @oleg-nenashev
=> Override URLs for plugins replaced by Warnings NG

src/main/resources/allowed-labels.properties
The change adds official support for the https://github.com/topics/jenkins-api-plugin GitHub topic which represents the "API Plugin" term we were using recently for plugins which do not provide their own user-facing functionality. 
Problem: it collides with https://plugins.jenkins.io/ui/search/?labels=library which used to be used for such purpose in Wiki. IMHO "library" is a bit confusing, e.g. see https://github.com/topics/jenkins-library which refers Pipeline or Groovy script libraries. Needs discussion with interested parties to decide.
CC @uhafner @jglick @bitwiseman @jeffret-b @jvz @kuisathaverat @wadeck  who maintain API plugins from the lists
=> Permit the API Plugin label

src/main/resources/allowed-labels.properties
https://github.com/search?q=topic%3Aemail+org%3Ajenkinsci&type=Repositories . There are actualy more plugins, but looks like we hit an issue with forked repositories which do not get listed. FYI @daniel-beck
=> Whitelist the email plugin label

src/main/resources/allowed-labels.properties
There are at least 5 plugins for OpenShift now: https://github.com/jenkinsci?q=openshift&type=&language= , so I think it would be nice to have a label on the plugin site
CC @olivergondza @akram
=> Add "openshift" to the list of allowed GitHub labels

src/main/resources/warnings.json
advisory: https://jenkins.io/security/advisory/2019-04-03/#SECURITY-1084
correction: https://github.com/jenkinsci/openid-plugin/pull/18
new release: https://github.com/jenkinsci/openid-plugin/releases/tag/openid-2.4
artifact: https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/General/releases/org/jenkins-ci/plugins/openid/2.4
=> Remove warning for openid

pom.xml, src/main/java/org/jvnet/hudson/update_center/Main.java, src/main/java/org/jvnet/hudson/update_center/Popularities.java
This addresses the problem encountered after merging #356: It looks like Jenkins will always create floats when deserializing / serializing JSON using json-lib.
These changes ensure that the update center creates the expected format.
=> Fix popularity: Actually create float output

src/main/resources/artifact-ignores.properties
Per https://jenkins.io/project/governance/#license we only distribute plugins with OSI approved licenses, and these plugins don't:
https://github.com/jenkinsci/ci-with-toad-devops-toolkit-plugin/blob/master/LICENSE
https://github.com/jenkinsci/ci-with-toad-edge-plugin/blob/master/LICENSE
FYI @jlibo-quest, @PChudani-Quest, @kdalton-Quest, @hamermike.
=> Suspend distribution of plugins with non OSI license

src/main/resources/warnings.json
The plugin had used `Secret`   to save sensitive information after version 2.0.0 .
=> [SECURITY-1423] Update pattern after fix in 2.0.0

src/main/resources/artifact-ignores.properties
Pick up a plugin suspension from https://github.com/jenkins-infra/update-center2/pull/365 to make current builds comparable; when I tried to use the new code I got checksum problems. This is the only effective change to current `update-center.*` in that PR.
=> Suspend distribution of aliyun-container-service-deploy due to ambiguity

README.adoc, resources/deprecations.properties, src/main/java/io/jenkins/update_center/Deprecations.java, src/main/java/io/jenkins/update_center/json/UpdateCenterDeprecation.java, src/main/java/io/jenkins/update_center/json/UpdateCenterRoot.java
Companion PR to https://github.com/jenkinsci/jenkins/pull/4073 for a basic implementation of [JENKINS-59136](https://issues.jenkins-ci.org/browse/JENKINS-59136).
---
Add support for marking any plugin artifact ID as deprecated, even those not currently published.
Broadly speaking, there are now two supported mechanisms for marking as deprecated:
* The label `deprecated`.
* Entries in a new top-level object `deprecations`, keys are plugin IDs, and values are objects with a key `url` whose value is a String.
The former requires no changes to the `update-center.json` format. This implements the latter.
There are two use cases for the top-level `deprecations` element:
* Deprecating plugins that are no longer published.
* Using a different deprecation reference URL than just the regular plugin …
=> [JENKINS-59136] Deprecation support

resources/artifact-ignores.properties
Since the release of 1.18 which is a year ago: https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.18
The code that was moved to other plugins where it belonged have had time to adopt.
I suggest we blacklist.
cc @timja
=> blacklist configuration-as-code-support

resources/artifact-ignores.properties
Apparently the plugin doesn't work anymore anyway.
https://www.jenkins.io/security/advisory/2020-06-03/
=> Stop distributing play-autotest plugin

resources/artifact-ignores.properties
Looks like both 1.0 and 1.0.0 were released and that creates ambiguity in what we publish:
https://github.com/jenkinsci/sideex-plugin/commits/master
From build logs and https://updates.jenkins.io/download/plugins/sideex/ it looks like 1.0 is currently being published at least fairly consistently, so choose that over 1.0.0.
FYI @kiam123, please don't create releases whose precedence is ambiguous (`X` and `X.0`).
=> Suspend distribution of sideex-1.0.0

site/README.md, site/generate-htaccess.sh, site/generate.sh, site/static/dynamic.html, site/test/test.sh
https://updates.jenkins.io/ is a mess 😮 So just hide most of it in one `dynamic/` top level directory.
=> Nest dynamic tier directories into common top-level directory

src/main/java/io/jenkins/update_center/json/TieredUpdateSitesGenerator.java
Sample output:
> `2020-08-03 17:50:08.774+0000 [id=1]     INFO    i.j.u.j.TieredUpdateSitesGenerator#update: Did not find declared core dependency version among all core releases: 2.185-rc28469.6af78cb11bf8. It is used by io.jenkins.plugins:build-symlink:1.0`
=> Identify which plugin releases have non-existing core dependencies

site/README.md, site/generate-htaccess.sh, site/generate.sh, site/static/dynamic.html, site/test/test.sh
This reverts commit 1a365ed13daa4de631c4023a55310221e9478704.
----
The mirroring script `sync.sh` does not supported update sites in nested folders (something like `for FILE in */update-center.json`). Rather than touch that, revert this change from #416. It seems to have weird performance effects anyway.
=> Revert "Nest dynamic tier directories into common top-level directory"

resources/deprecations.properties, resources/label-definitions.properties
Followup to #405, supersedes #422.
I'd like a better URL, but the wiki page is out (thanks redirect rules!), and https://github.com/jenkinsci/sonargraph-plugin/ has nothing.
Perhaps @andreashoyerh2m can provide a better reference, e.g. update the old plugin's readme in the repo, but for now, this will do.
=> Properly mark sonargraph-plugin as deprecated

resources/allowed-github-topics.properties
Add `redis` to allowed-github-topics.properties
CC @oleg-nenashev @afalko @mikecirioli
=> Add redis to allowed-github-topics

site/generate-htaccess.sh
````
$ curl -IL http://localhost:8080/download/plugins/git/latest/git.hpi
HTTP/1.1 302 Found
Date: Mon, 24 Aug 2020 20:33:07 GMT
Server: Apache/2.4.43 (Unix)
Location: https://updates.jenkins.io/latest/git.hpi
Content-Type: text/html; charset=iso-8859-1
HTTP/1.1 302 Found
Date: Mon, 24 Aug 2020 20:33:08 GMT
Server: Apache/2.4.29 (Ubuntu)
Location: https://updates.jenkins.io/download/plugins/git/4.3.0/git.hpi
Content-Type: text/html; charset=iso-8859-1
HTTP/1.1 302 Found
Date: Mon, 24 Aug 2020 20:33:08 GMT
Server: Apache/2.4.29 (Ubuntu)
Location: https://get.jenkins.io/plugins/git/4.3.0/git.hpi
Content-Type: text/html; charset=iso-8859-1
HTTP/2 302 
server: nginx/1.19.1
date: Mon, 24 Aug 2020 20:33:09 GMT
content-type: text/html; charset=utf-8
location: …
```
=> Add local redirect to make 'latest' links work even with bad mirrors

site/generate.sh
This implements the suggestion in https://github.com/jenkinsci/docker/issues/954#issuecomment-646254122 and  will result in the gradual retirement of fixed tiers.
Currently, all five latest fixed tiers are still generated for tools and scripts accessing them directly. With 2.249.x coming in ~5 weeks, 2.176.x will be retired, but 2.249.x would _not_ be added with this change. This would continue until, after about a year, no fixed tiers are generated anymore.
https://github.com/jenkinsci/docker/issues/954 should be implemented so the Docker image doesn't require these directories anymore. CC @slide
=> [INFRA-2615] Deprecate fixed tiers, don't generate for 2.249.x+

resources/artifact-ignores.properties
https://www.jenkins.io/security/advisory/2020-09-01/#SECURITY-1905 is pretty serious, and the plugin doesn't really matter, so best to suspend it. Didn't get this prepared in time for the advisory publication earlier today.
Related to https://github.com/jenkins-infra/jenkins.io/pull/3681 (which will fix up the plugin name once this is merged)
=> Suspend distribution of JSGames plugin

resources/warnings.json
CC @Igor-Filin
We'll need to confirm the issue is fully resolved first, and if it is, we'll merge this to disable the active security warning.
=> [SECURITY-1686] Disable warning for 2.5.1+

src/main/java/io/jenkins/update_center/HPI.java, src/test/java/io/jenkins/update_center/SanitizerTest.java
Quite a few plugin descriptions contain an HTML link to the service's website or similar.
This change modifies these links to always have `target="_blank"`, and set `rel="noopener noreferrer"` in addition to `rel="nofollow"` (the default, doesn't really matter).
=> Add target=_blank for all links in plugin descriptions

resources/deprecations.properties
See [JENKINS-56773](https://issues.jenkins-ci.org/browse/JENKINS-56773).
=> [JENKINS-56773] Add deprecation for blueocean-executor-info

resources/artifact-ignores.properties
Reference: https://github.com/jenkinsci/qualys-api-security-plugin/commits/master
I really need to get #412 over the finish line.
FYI @nikita-bedmutha please re-release 2.1.0 as 2.1.1.
=> Suspend distribution of qualys-api-security-2.1.0 due to ambiguous version

resources/artifact-ignores.properties
[JENKINS-63877](https://issues.jenkins-ci.org/browse/JENKINS-63877)
Temporary measure to restore plugin manager operation.
@jglick
=> [JENKINS-63877] Suspend distribution of tics plugin

resources/artifact-ignores.properties
Ignore spotinst version 2.0.26
This release update node details and by that causing Jenkins to reset its computer
=> Ignore spotinst version 2.0.26

resources/warnings.json
The SECURITY-1014 vulnerabilities were fixed in Libvirt Agents plugin
version 1.9.0.  Match only for the vulnerable versions in order to warn.
=> [SECURITY-1014] Match vulnerable Libvirt Agents

resources/warnings.json
According to the maintainer, SECURITY-1520 is resolved in the 2.0.0 release of the plugin.
=> [SECURITY-1520] Update warning for repository-connector

resources/deprecations.properties
This will add a deprecation warning to https://plugins.jenkins.io/brakeman/ (and inside Jenkins) similar to https://plugins.jenkins.io/analysis-core/
It's a bit redundant, given the dependency, but cannot hurt. It also links to the issue that explains what users can do instead now (and will continue to show up even once distribution has been suspended for INFRA-2487).
@presidentbeef @uhafner
=> [INFRA-2487] Mark brakeman plugin as deprecated

resources/artifact-ignores.properties, resources/deprecations.properties
The app.io service was discontinued. Based on alternatives suggested in [a Quora thread](https://www.quora.com/What-is-a-good-alternative-to-replace-App-io-embedded-demo-pages-which-have-been-discontinued) the users of this plugin may be interested in using appetize.io and the [Appetize.io Jenkins Plugin](https://plugins.jenkins.io/appetize/) instead.
=> Remove app.io plugin from distribution

resources/artifact-ignores.properties, resources/deprecations.properties
This will remove the plugins from update sites, and all instances with one of these plugins installed will show a deprecation message linking to INFRA-2487.
@uhafner @MarkEWaite @oleg-nenashev
=> [INFRA-2487] Suspend analysis-core and all dependent plugins

resources/allowed-github-topics.properties
Add `fingerprint` to allowed-github-topics.properties
CC @oleg-nenashev @afalko @mikecirioli
=> Add fingerprint to allowed-github-topics

resources/artifact-ignores.properties
https://issues.jenkins.io/browse/INFRA-2838
The last 2 releases of nexus-jenkins-plugin don't have a pom file which causes update-center2 generation to break.
The next release back [3.9.20201203-120425.a87655e](https://repo.jenkins-ci.org/releases/org/sonatype/nexus/ci/nexus-jenkins-plugin/3.9.20201203-120425.a87655e/) has a pom file but no jar or sources, not sure if that needs blocking too
cc @whyjustin
p.s. where are the sources of this plugin? I can't find them and they aren't linked on the plugin site
=> [INFRA-2838] Block broken releases of nexus-jenkins-plugin

site/generate.sh
Part of the workaround when the cert expired the last time.
This should change the date the build will start failing next from 2021-04-02 to 2021-03-17. Then we'll need a new yearly cert based on the new root cert https://github.com/jenkins-infra/update-center2/tree/master/resources/certificates#jenkins-update-center-root-ca-2
=> Stop overriding the expected validity duration of the signing cert

site/generate-htaccess.sh, site/test/test.sh
https://github.com/jenkinsci/jenkins/pull/5106#issuecomment-743093376 points out that redirects don't work for snapshot versions (any more?).
=> Add support for snapshot versions

resources/artifact-ignores.properties
`tics` version 2020.3.0.7 has been fixed to no longer have a dependency on itself.
https://issues.jenkins.io/browse/HOSTING-1021 has some related discussion.
=> Restore distribution of tics plugin with fixed dependencies

resources/artifact-ignores.properties
@bitwiseman 
We have no good way to inform users they have a bad release installed. The usual resolution is to publish a new version. Versions that have been used are burned afterwards. My general advice in such cases is to accept the mistake and move on with the new version numbers; it's simply unfortunate that the versioning scheme used here makes that awkward.
Unsure what the best way forward is; if it is to suspend 1.222, it should be done ASAP.
=> Suspend distribution of github-api 1.222

resources/wiki-overrides.properties
These plugins have meanwhile released a version with either the exact same URL or a better one (moving docs to GitHub).
=> Remove unnecessary overrides

resources/warnings.json
A current limitation of the warnings system is that we cannot check whether a previous version of the plugin has been installed before, and only warn then. This can matter if the problem is data previously written to disk. So we just warn for every release.
These warnings lose their usefulness over time: At some point, probably a few months later, we can assume everyone who would be affected has been informed about it, or will never be informed (e.g. third party update sites). At the same time, active warnings can be confusing people, as indicated by https://github.com/jenkinsci/ghprb-plugin/issues/805#issuecomment-778330826
Another option would be to phrase such warnings differently to make it clear it's about data stored in releases before …; but at least in this case it's been long …
=> [SECURITY-261] Limit affected versions to those creating the problem

resources/artifact-ignores.properties
Pending https://github.com/jenkinsci/jenkins/pull/5304 @timja. Basically it is necessary to fully test the core patch _before_ releasing the plugin for the first time, using Incrementals.
=> Suppress instance-identity plugin releases

README.adoc, resources/allowed-github-topics.properties, resources/warnings.json, site/LAYOUT.md, src/main/java/io/jenkins/update_center/Main.java, src/main/java/io/jenkins/update_center/wrappers/AllowedArtifactsListMavenRepository.java
* Renamed the "whitelist" related code (mostly development helper) to more precise "allowed artifacts list"
* Updated security warning titles, in many cases updating to match an earlier change to jenkins-infra/jenkins.io (a bunch of "master" occurrences, mostly)
* Call the GitHub topics list an allowlist
What's left:
* `master` branch is still used for now
* Offensive labels are still defined and allowed, that's being cleaned up in in #353
* Any references to plugins whose ID includes any of these terms will continue to exist until they've been renamed
FYI @MarkEWaite
=> Replace obsolete terminology

resources/artifact-ignores.properties
https://updates.jenkins.io/download/plugins/ca-mat-performance-benchmarking-by-broadcom/1.2/ca-mat-performance-benchmarking-by-broadcom.hpi is not even close to a valid HPI file. Probably related to the release trouble mentioned in https://github.com/jenkins-infra/repository-permissions-updater/pull/1844.
While this isn't advertised to instances, it still shows in https://updates.jenkins.io/download/plugins/ca-mat-performance-benchmarking-by-broadcom/
FYI @pessoarthur
=> Ignore ca-mat-performance-benchmarking-by-broadcom-1.2

README.adoc, src/main/java/io/jenkins/update_center/IssueTrackerSource.java, src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java
See [INFRA-2928](https://issues.jenkins.io/browse/INFRA-2928). Supersedes (mostly) https://github.com/jenkins-infra/update-center2/pull/461. Downstream from https://github.com/jenkins-infra/repository-permissions-updater/pull/1806.
This adds a new entry `issueTrackers` to plugin metadata that closely resembles the upstream output format described in https://github.com/jenkins-infra/repository-permissions-updater#consuming-issue-trackers, except this drops the `reference` entry. `type` is kept to allow for UI labels related to that.
CC @halkeye @timja
=> [INFRA-2928] Add issue tracker metadata

site/generate.sh
We're getting a new root cert soon for [INFRA-1502](https://issues.jenkins.io/browse/INFRA-1502), see https://www.jenkins.io/blog/2021/03/15/update-center-certificate-rotation/
Meanwhile, we need to accept a shorter validity duration by basically reverting #471.
=> [INFRA-1502] Reduce certificate validity duration to 2 weeks

README.adoc, src/main/java/io/jenkins/update_center/GitHubSource.java, src/main/java/io/jenkins/update_center/HPI.java, src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java, src/test/java/io/jenkins/update_center/GitHubSourceTest.java, src/test/resources/github_graphql_Y3Vyc29yOnYyOpHOA0oRaA==.txt, src/test/resources/github_graphql_null.txt
See [INFRA-2929](https://issues.jenkins.io/browse/INFRA-2929).
Implements the rest of https://github.com/jenkins-infra/update-center2/pull/461 after https://github.com/jenkins-infra/update-center2/pull/492 takes care of issue tracker metadata via a different approach.
=> [INFRA-2929] Expose default branch in GitHub

site/generate.sh, src/main/java/io/jenkins/update_center/json/RecentReleasesRoot.java
This will more easily allow overriding how far back `recent-releases.json` looks for artifacts to include.
Useful in cases where the build failed for a while, like today, and `recent-releases.json` wouldn't cover everything. Previously, this would require patching the application and creating a new release.
----
Alternatively (and this is what I was doing today) we can patch the application locally and just run it with
```
--generate-recent-releases --skip-update-center  --www-dir ./recent
```
only generating a more comprehensive `recent-releases.json` file; which is barely more work than passing a system property.
=> Allow overriding max age for recent releases

README.adoc, src/main/java/io/jenkins/update_center/HPI.java, src/main/java/io/jenkins/update_center/MaintainersSource.java, src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java, src/test/java/io/jenkins/update_center/MaintainersSourceTest.java
Downstream of https://github.com/jenkins-infra/repository-permissions-updater/pull/1880 and https://github.com/jenkins-infra/infra-reports/pull/27
PR currently fails because of infra not yet having the ID/display name maintainer mapping because trusted.ci is down, so a test assertion fails.
=> Use RPU permissions for 'developers' instead of Maven metadata

site/generate.sh
https://issues.jenkins.io/browse/INFRA-1502
The infra team switched over to the new root cert on Monday as announced on https://www.jenkins.io/blog/2021/03/15/update-center-certificate-rotation/ and since then `update-center2` builds have shown signature validation failures because it tries to validate a new yearly cert against the old root certificate 🤦 
This fixes that.
Applied it from this origin branch, and it works 🎉 
Delete after merge (but don't forget to switch the job back).
=> [INFRA-1502] Perform validation with new root certificate

site/generate.sh
Fixes the rendering of https://updates.jenkins.io so that it will look like the usual page rather than looking like this:
=> Switch to using wget with convert links to make sure index.html has absolute urls to the jenkins.io assets

resources/warnings.json
Apparently this is fixed in version 2.5 of the plugin.
I'll confirm that and then merge this PR.
=> Note fix of SECURITY-1510 in backlog plugin

resources/platform-plugins.json, src/main/java/io/jenkins/update_center/Main.java, src/main/java/io/jenkins/update_center/json/PlatformCategory.java, src/main/java/io/jenkins/update_center/json/PlatformPlugin.java, src/main/java/io/jenkins/update_center/json/PlatformPluginsRoot.java
This adds support for serving a statically defined `platform-plugins.json` with a new wrapper object that includes a signature to basically serve as a PoC for a corresponding core change.
This does _not_ add support for generating such files to the wrapper scripts or `.htaccess`, but both changes combined prepare for a future change that provides such `platform-plugins.json` via update sites (that could then also distinguish content by reported client version).
=> [INFRA-2937] Add support for generating platform-plugins.json

src/main/java/io/jenkins/update_center/json/WithSignature.java, src/test/java/io/jenkins/update_center/TimestampTest.java
This will allow consumers to figure out if they get outdated data. We could even use it for an infra probe given recent trusted.ci stability problems 😓
Output (excerpt):
```
{
"connectionCheckUrl": "http://www.google.com/",
"core": {
"buildDate": "Apr 20, 2021",
"name": "core",
"sha1": "4CUREvEyDp+w5LnceNb5v4Z25ak=",
"sha256": "nBz97VAlE/o1eAcLDEynxGE6eKvxhI1Ug7DvAsE0J8g=",
"url": "https://updates.jenkins.io/download/war/2.289/jenkins.war",
"version": "2.289"
},
"deprecations": {
...
},
"generationTimestamp": "2021-04-26T19:08:45.177Z",
```
=> Add generation timestamp to metadata

resources/deprecations.properties
This should cover all suspended plugins with >200 (0.07%) known installs.
=> Add deprecation links for suspended plugins

resources/warnings.json
Better late than never I guess?
With the deprecation of the Overall/RunScripts permission from Jenkins in [2.222](https://www.jenkins.io/changelog-old/#v2.222) (which effectively removed them and granted every admin the same level of permissions even in crazy environments), there is no longer a need to warn about these.
While most of these plugins addressed the problematic behaviors, https://plugins.jenkins.io/extreme-notification/ and https://plugins.jenkins.io/shared-objects/ still show these warnings. `app-detector` got suspended for a more critical code execution vulnerability, the "admin" one was only secondary.
=> Remove 'rare circumstances' RCE warnings

resources/artifact-ignores.properties
We have updated the license to OSI approved for ci-with-toad-edge plugin.
https://github.com/jenkinsci/ci-with-toad-edge-plugin/blob/master/LICENSE
With ci-with-toad-edge-2.2, we have fixed the license issue.
Please merge this PR.
=> remove ci-with-toad-edge from list of suspended plugin and suspend specific plugin versions

resources/deprecations.properties
In recent core PRs jenkinsci/jenkins#5320, jenkinsci/jenkins#5338, jenkinsci/jenkins#5521, and jenkinsci/jenkins#5526, we are intentionally leaving behind 15 plugins. These plugins are unmaintained, and they have not seen commits or releases in years. Even when we opened PRs against them, these PRs went unacknowledged. We have judged that the benefit of supporting these plugins is not worth the cost to ongoing maintenance.
We do our users a disservice by not explicitly marking these plugins as deprecated. These plugins are, de facto, unsupported. It may not be ideal, but this is the status quo and the reality. Users should be warned when installing these plugins for the first time, and users who have them already installed should be warned that these plugins may cause problems.
I am …
=> Formally deprecating plugins left behind in recent core PRs

resources/warnings.json
The maintainer filed [SECURITY-2354](https://issues.jenkins.io/browse/SECURITY-2354) and informed us there that this was fixed.
=> Note SECURITY-832 being fixed in snsnotify 2.0

resources/deprecations.properties
Although included in the primary list of candidates for deprecation due to jenkinsci/jenkins#5320, the plugin was fixed on its 1.10 release on June 3, and removed from the list (see https://github.com/bitwiseman/jep/tree/00c184f97f40c5f79f8f83074c78dd4fb1e1ac43/jep/231)
The plugin does have mantainers and is not deprecated.
=> GeneXus plugin is not deprecated

resources/artifact-ignores.properties
The job keeps failing with 
`Caused by: java.io.IOException: Failed to retrieve content of https://repo.jenkins-ci.org/releases/io/jenkins/plugins/tuleap-api/2.3.0/tuleap-api-2.3.0.pom `
=> Disable all tuleap

resources/deprecations.properties
As of [commit 20e1449](https://github.com/jenkinsci/coding-webhook-plugin/commit/20e1449513628ad24476b47331ea7bd6a2e82583) by @tsl0922 Coding Webhook has been "archived in favor of coding's [official jenkins integration](https://help.coding.net/docs/project-settings/service-hook/service.html#jenkins)."
=> Deprecating Coding Webhook

site/generate.sh
`.htaccess` rules redirect requests to files in `/stable/` to the latest `dynamic-stable-2.xyz.w`, but the actual directory is built on a really old branch, so the contents of https://updates.jenkins.io/stable/ don't look like https://updates.jenkins.io/dynamic-stable-2.289.1/ (see file sizes).
This PR aims to change that.
=> Determine stable/ directory based on last dynamic LTS

README.adoc, resources/artifact-ignores.properties, resources/deprecations.properties, src/main/java/io/jenkins/update_center/BaseMavenRepository.java, src/main/java/io/jenkins/update_center/Deprecations.java, src/main/java/io/jenkins/update_center/json/UpdateCenterRoot.java, src/test/java/io/jenkins/update_center/DeprecationTest.java
@daniel-beck this should make it easier to inform users about suspended plugins (no duplication between ignores and deprecations). General thoughts 👍 / 👎 ? If it's OK I'll double-check that no information got lost here.
=> Remove duplication between deprecations and ignores

resources/deprecations.properties
From [JEP-7](https://github.com/jenkinsci/jep/tree/70474800713263f42e20ca549f7c8a52e3dfec19/jep/7):
> Plugins will be deprecated in the Update site immediately after the announcement. The deprecation notice will reference the announcement blogpost as justification.
@halkeye does not appear to have completed this task. :man_shrugging:
=> Deprecating non-Java plugins

resources/artifact-ignores.properties
Since https://github.com/jenkinsci/aws-java-sdk-plugin/pull/540 these plugins are no longer released separately, they are all part of https://plugins.jenkins.io/aws-java-sdk-minimal . I think it's safe to just remove them since nothing depends on them, but if the preference is to deprecate for a while, remove later, I can do that instead.
@vlatombe OK?
CC @daniel-beck
=> Remove unused AWS API plugins

resources/artifact-ignores.properties, resources/deprecations.properties
And it came to pass [at the end of thirty days](https://www.jenkins.io/blog/2021/12/22/deprecated-ruby-runtime/) that no users complained about the deprecation of non-Java plugins. And @basil said, may these plugins be suspended from distribution. And it was so, and no longer did the non-Java plugins roam the face of the earth.
CC @daniel-beck @halkeye
=> Suspend distribution of non-Java plugins

resources/artifact-ignores.properties
https://github.com/jenkins-infra/update-center2/pull/473 all over again.
I propose next time we suspend the entire plugin.
=> Suspend nexus-jenkins-plugin-3.13.20220124-204320.8222771 without pom

resources/artifact-ignores.properties
Per their own documentation on the wiki page https://github.com/jenkins-infra/docker-confluence-data/blob/main/content/JENKINS/StarTeam.html currently rendered on https://plugins.jenkins.io/starteam/ :
> <img width="854" alt="Screenshot 2022-02-21 at 14 21 08" src="https://user-images.githubusercontent.com/1831569/154963698-ee228e02-832c-48df-83b6-1d6578a49488.png">
The last release in https://github.com/jenkinsci/starteam-plugin/commits/master was 0.6.12 in 2013, so suspend distribution.
=> Suspend distribution of StarTeam plugin, it's closed source since 2015

resources/artifact-ignores.properties, resources/warnings.json
FYI @gmcdonald @olamy 
Corrections:
- SECURITY-2287, https://github.com/jenkinsci/publish-over-ssh-plugin/pull/50 and https://github.com/jenkinsci/publish-over-ssh-plugin/pull/59
- SECURITY-2290, https://github.com/jenkinsci/publish-over-ssh-plugin/pull/51 and https://github.com/jenkinsci/publish-over-ssh-plugin/pull/58
- SECURITY-2291, https://github.com/jenkinsci/publish-over-ssh-plugin/pull/52
- SECURITY-2307, https://github.com/jenkinsci/publish-over-ssh-plugin/pull/54
Fix version with the fixes: 1.24
With its companion to remove the entry in the https://www.jenkins.io/security/plugins/#suspensions list: https://github.com/jenkins-infra/jenkins.io/pull/4940
=> Unsuspend publish-over-ssh since 1.24

resources/artifact-ignores.properties
Admittedly our infra is more brittle than it should be, but it works well enough for basically every plugin/maintainer.
After https://github.com/jenkins-infra/update-center2/pull/473 and https://github.com/jenkins-infra/update-center2/pull/566, today is yet another time that bad release content of `nexus-jenkins-plugins` breaks the generation ([first because `.hpi` was uploaded 45+ minutes after the `.pom`, then because it's a 0 byte file](https://repo.jenkins-ci.org/releases/org/sonatype/nexus/ci/nexus-jenkins-plugin/3.13.20220304-155321.e7fcac5/)), so I propose we suspend the plugin.
The plugin should be updated to be released using JEP-229 CD, so that whatever is currently going on here stops.
FYI @eduard-tita
=> Suspend nexus-jenkins-plugin

resources/artifact-ignores.properties
Reverts jenkins-infra/update-center2#576
Given https://groups.google.com/g/jenkinsci-dev/c/TZakKUjUm9Q/m/Pirq0fqEBAAJ it's possible this failed release is not (only) caused by the maintainer/release process side of things, so reverting this and instead only suspend the known broken release.
=> Revert "Suspend nexus-jenkins-plugin"

resources/artifact-ignores.properties
The March 25, 2022 release of [agc-app-upload 1.0](https://repo.jenkins-ci.org/artifactory/releases/com/huawei/jenkins/agc-app-upload/1.0/) includes only the hpi file, but not the pom file.  Without the pom file, the update center job fails.
=> Exclude agc-app-upload 1.0, includes no pom file

resources/artifact-ignores.properties, resources/deprecations.properties
git.io is deprecated since January 2022 and now scheduled for sunset on the 29th of April.
See the relevant blogpost: https://github.blog/changelog/2022-04-25-git-io-deprecation/
I went ahead and replaced all git.io URLs in this repository to not be impacted by the forthcoming change.
=> Address git.io deprecation

resources/artifact-ignores.properties
This PR depublishes https://plugins.jenkins.io/jx-pipelines/ and https://plugins.jenkins.io/jx-resources/.
These plugins have been obsolete since Jenkins X removed support for static Jenkins controllers around April 2020. See https://github.com/jenkins-x/jx/issues/7020 and https://jenkins-x.io/blog/2020/03/11/tekton/. My understanding is that `jx-pipelines` was technically obsolete even before that, see https://github.com/jenkins-x/jenkins-x-image/pull/8.
=> Depublish jx-pipelines and jx-resources

resources/artifact-ignores.properties
These artifact IDs are obsolete after these PRs:
* https://github.com/jenkins-infra/repository-permissions-updater/pull/1461
* https://github.com/jenkins-infra/repository-permissions-updater/pull/1379 + https://github.com/jenkins-infra/repository-permissions-updater/pull/1418
CC @iTMSJenkins @castnightlybuild
=> Suspend castecho and itms-junit-report-publisher after rename

resources/artifact-ignores.properties
Realized post release that https://github.com/jenkinsci/workflow-api-plugin/pull/221 would be offered to 2.289.x–2.319.x UCs without https://github.com/jenkinsci/workflow-cps-plugin/pull/534 which it requires to avoid some anomalous behavior. Best to block it from those lines, and let 2.332.x— pick up https://github.com/jenkinsci/workflow-api-plugin/pull/226. @dwnusbaum @car-roll
=> Block `workflow-api` at `1162.va_1e49062a_00e`

src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
Fixes https://github.com/jenkins-infra/helpdesk/issues/1968 by making all cache files have 64-char names. **Untested.**
=> Switch cache to SHA-256

resources/deprecations.properties
The way form validation works in Jenkins is changing as part of https://github.com/jenkinsci/jenkins/pull/6460, 'bmc-rpd-plugin' uses custom logic in this area and as such won't work when 6460 is merged. 
Due to the plugins age and inactivity (six years) and that it has an active security warning it's been decided to deprecate the plugin.
----
The corresponding core PR was merged in 2.355, https://www.jenkins.io/changelog/#v2.355
=> Deprecate bmc-rpd-plugin

resources/deprecations.properties
JNR was removed in https://github.com/jenkinsci/jenkins/pull/6323. https://github.com/jenkinsci/maven-repo-cleaner-plugin/pull/4 dropped the dependency on JNR in Maven Repository Scheduled Cleanup, and that PR was merged on June 26, 2018; however, it has not been released.
=> Deprecate Maven Repository Scheduled Cleanup

resources/artifact-ignores.properties
We invoke `ln` with the version number as second arg without `--`, so `ln` thinks this is a flag. That'll be the proper fix (or, even properer, apply https://github.com/jenkins-infra/update-center2/pull/569), but for now this needs to work again to unblock today's security advisory delivery.
FYI @delanAtMergebase, we'll readmit your plugin later today or tomorrow once we've made this tool more robust.
=> Block mergebase-sca because its version numbers cause trouble

resources/artifact-ignores.properties
While the Java 11 requirement is documented in https://github.com/jenkinsci/trilead-api-plugin/releases/tag/1.71.v9e7860a_67a_df, the plugin does not require a Java 11 only release of Jenkins, and does not set the incompatibility flag (whose message wouldn't be great but at least folks would read the changelog).
I suggest we do the following:
* Suspend this release of `trilead-api`
* @kuisathaverat bumps the core dependency of `trilead-api` to 2.357 so it's only offered to Java 11 only update sites.
Thoughts?
=> [JENKINS-69229] Suspend distribution of trilead-api-1.71.v9e7860a_67a_df

resources/artifact-ignores.properties
Short URLs were nice to save bytes on `update-center.json`, but they no longer work.
=> Replace broken wiki short URLs with full URLs

pom.xml, spotbugs-excludes.xml, src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java, src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java
Use the current parent pom and other dependencies.  Update the spotbugs exclusions for new warnings reported with the most recent spotbugs.  Create symbolic links and hard links with Java NIO methods instead of making calls to the operating system.  The change to Java NIO calls avoids a spotbugs warning related to ProcessBuilder command injection.
Exclude okhttp and annotation-api from fastjson because newer versions are being provided by other dependencies.
Update owasp-java-html-sanitizer to 20211018.2 to resolve a security warning.
- Use fastjson 1.2.79, not 1.2.73
- Use okhttp-urlconnection 4.9.3, not 4.8.0
- Use commons-io 2.11.0, not 2.7
- Use commons-lang3 3.12.0, not 3.11
- Use commons-codec 1.15, not 1.14
- Use support-log-formatter 1.1, not 1.0
- Use version-number 1.9, not 1.7 …
=> Simplify symlink creation, update dependencies

src/main/java/io/jenkins/update_center/HPI.java, src/main/java/io/jenkins/update_center/MaintainersSource.java
Currently https://reports.jenkins.io/maintainers-info-report.json contains
```
{
"name": "thycotic_dsv",
"displayName": "Thycotic Dev"
},
{
"name": "thycotic_dsv",
"displayName": "Thycotic Dev"
},
```
which breaks getting display names for all maintainers (all are null in https://updates.jenkins.io/current/update-center.actual.json )
This makes parsing of the display names more robust, duplicates will only be reported in the log and not fail the whole parsing process.
Also removes unused `Developer` since it was replaced by `Maintainer`.
CC @daniel-beck
=> Handle duplicate maintainer entries

src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
https://updates.jenkins.io didn't update for several hours today (1:42 PM to 9:30 PM), discovered via https://groups.google.com/g/jenkinsci-dev/c/qFIOBwWCLyM/m/63OkleJfAQAJ
Root cause was that the tool cached a failure to download the `.pom` file of today's release of https://plugins.jenkins.io/git-automerger/
Since that is a stupid reason to stop working, this change discards all plugin `.hpi`/`.jpi` (and core `.war`) files without a corresponding `.pom` file. This typically should only filter out files for one run due to upload timing issues, or remove plugins that are improperly uploaded.
Untested.
=> Discard hpi/jpi/war artifacts without corresponding pom file

src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java
The Java API does not overwrite existing symlinks, so we need to delete what's there first.
Also add better logging when things go wrong.
Amends #569.
=> Fix symlink creation when it already exists

src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java
Not fatal, but still annoying.
I doubt absolute file paths (following certain rules) can be used to inject unsafe behavior into an invocation of `ln`.
Amends #633, #569.
=> Suppress FB warning about ProcessBuilder invoking ln

src/main/java/io/jenkins/update_center/Main.java, src/main/java/io/jenkins/update_center/args4j/Default.java
Amends #561.
Without this, using `--arguments-file` with reset the arguments to `null`.
There's redundancy between the annotation and the actual field. This isn't great but I couldn't think quickly of a way to record default values, and args4j prints field values as part of `--help` output, so leaving the fields at their empty default would be misleading.
=> Do not wipe options with default values when using --arguments-file

resources/artifact-ignores.properties
The plugin is incompatible with JEP-200, Jenkins 2.266+ (it hardcodes the `j_acegi_security_check` URL), and possibly even always-on CSRF protection (2.222+); so it doesn't really make sense to continue distributing it.
The maintainer asked that we suspend distribution with the following explanation:
> The tool it is associated with has moved to a different authentication path than the plugin currently supports, making the plugin no longer valid for use against the tool. As such are no longer looking to support, distribute, or update the plugin.
The domain walti.io is for sale, the service seems to no longer exist.
=> Suspend distribution of build-publisher, cons3rt, walti

resources/artifact-ignores.properties
Suspend distribution of plugins with long-standing global configuration issues due to the tables to divs transition in Jenkins 2.277.1.  Stop distributing plugins that block global configuration save for actively maintained Jenkins versions.
All the suspended plugins have decreasing installation counts over the last 12 months.  That is expected because users detect the problem and remove the plugin from their installation when they upgrade to Jenkins 2.277.1 or later.
Suspended plugins include:
* [aws-sqs](https://plugins.jenkins.io/aws-sqs/) - [JENKINS-65834](https://issues.jenkins.io/browse/JENKINS-65834)
* [github-sqs-plugin](https://plugins.jenkins.io/github-sqs-plugin/) - [JENKINS-65729](https://issues.jenkins.io/browse/JENKINS-65729)
* …
=> Suspend plugins that block global config save

resources/artifact-ignores.properties
[JENKINS-69164](https://issues.jenkins.io/browse/JENKINS-69164)
Amends #626.
https://github.com/jenkinsci/katalon-plugin/pull/25 updates the utils library to include https://github.com/katalon-studio/utils/releases/tag/v1.0.16
CC @halkeye @MarkEWaite
=> [JENKINS-69164] Restore distribution of Katalon (only suspend old releases)

resources/artifact-ignores.properties
Warnings update to follow (too lazy to write it myself, and the script we have needs to have the plugin distributed).
=> Restore distribution of neuvector-vulnerability-scanner

resources/warnings.json
[SECURITY-2865](https://www.jenkins.io/security/advisory/2022-10-19/#SECURITY-2865) is addressed in 1.22: https://github.com/jenkinsci/neuvector-vulnerability-scanner-plugin/compare/neuvector-vulnerability-scanner-1.21...neuvector-vulnerability-scanner-1.22
=> Update warning for neuvector-vulnerability-scanner / SECURITY-2865

resources/artifact-ignores.properties
This plugin [does not work and has never worked unless used with `hpi:run`](https://github.com/jenkinsci/bart-plugin/blob/30d19e0ded8588c84601c7ffbcd0dd91c08ef945/src/main/java/org/jenkinsci/plugins/bart/LogParserBuildAction.java#L85). Given the age and low (single digit) install count, suspend it.
When the maintainer responded to [SECURITY-2937](https://www.jenkins.io/security/advisory/2022-11-15/#SECURITY-2937), they asked that the plugin be suspended (#651) and archived the repo already: https://github.com/jenkinsci/osf-builder-suite-xml-linter-plugin
Supersedes #651.
=> Add suspensions for additional plugins after 2022-11-15 advisory

resources/warnings.json
This CVE was fixed in https://github.com/jenkinsci/jenkins-cloudformation-plugin/pull/58 and released in version [1.4196.v59065a_32f38a](https://github.com/jenkinsci/jenkins-cloudformation-plugin/releases/tag/1.4196.v59065a_32f38a).
=> Mark warning as fixed for cloudformation plugin

resources/artifact-ignores.properties
According to the [repository readme](https://github.com/jenkinsci/cloudbees-plugin-gateway/blob/master/README.md), the plugin is already removed from the update center when it's not.
This PR suspends future installations, provided the service the plugin builds upon has shut down.
=> Suspend cloudbees-plugin-gateway

resources/artifact-ignores.properties
Since https://bearychat.com has been closed in last few years, this plugins is out-of-maintain and no longer available.
=> Remove BearyChat plugin from distribution

resources/deprecations.properties
Handlebars 3 is [abandoned](https://github.com/handlebars-lang/handlebars.js/tree/3.x), [has unresolved vulnerabilities](https://github.com/handlebars-lang/handlebars.js/issues/1736#issuecomment-836430832), and [no other plugin depends on this one anymore](https://plugins.jenkins.io/handlebars/#dependencies).
So far only marking it as deprecated instead of suspending distribution, but could go either way. CasC would probably be impacted by the latter?
Maintainers @batmat @rsandell to approve this PR.
=> Deprecate handlebars plugin

resources/artifact-ignores.properties
We have been notified by the maintainers that this plugin is no longer maintained and that they wish to depublish it.
=> Suspend keycloak plugin

resources/artifact-ignores.properties
https://github.com/jenkinsci/remoting-security-workaround-plugin was only ever intended as a temporary workaround for admins unable to immediately update to Jenkins 2.303.3 or 2.319.
Those releases are now long obsolete and no longer supported by update center tiers, and by now most users of the plugin have updated to releases with fixes anyway: https://stats.jenkins.io/pluginversions/remoting-security-workaround.html
For that reason, it makes no sense to continue distributing this plugin.
=> Suspend Remoting Security Workaround Plugin

resources/artifact-ignores.properties
The service is EOL according to the readme linked, and the repository has been archived.
https://github.com/jenkinsci/lightstep-incident-response-plugin
cc https://github.com/jenkins-infra/repository-permissions-updater/issues/3022 for cross-linking.
=> Suspend lightstep-incident-response plugin

resources/deprecations.properties
As of https://github.com/jenkinsci/workflow-cps-plugin/releases/tag/3611.v201b_d9f9eb_f7, Pipeline: Groovy Plugin no longer depends on `ace-editor`, making it a library plugin without dependents that can safely be uninstalled by everyone who's keeping their Jenkins up to date.
This is the last plugin in https://github.com/jenkinsci/js-libs/ to be deprecated (after #679 and #677); perhaps we can consider archiving this repo?
Maintainers @batmat @rsandell to approve.
Thanks @basil for making this possible.
=> Deprecate `ace-editor`

resources/warnings.json
The maintainers informed us that SECURITY-2910 (2) was resolved.
It looks like https://github.com/jenkinsci/cavisson-ns-nd-integration-plugin/commit/3aecf18565ab399f7e37240412a1745fc4338164 in 4.8.0.149 did it.
=> [SECURITY-2910] Mark (2) fixed in 4.8.0.149

src/main/java/io/jenkins/update_center/GitHubSource.java
Fixes https://github.com/jenkins-infra/helpdesk/issues/3190 (when running locally).
Though it is a workaround for a GitHub issue, it may still be worth merging since it makes the code more deterministic.
=> Query repositories in alphabetical order

src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java, src/main/java/io/jenkins/update_center/HPI.java, src/main/java/io/jenkins/update_center/Plugin.java, src/main/java/io/jenkins/update_center/PluginUpdateCenterEntry.java, src/main/java/io/jenkins/update_center/json/PluginVersionsRoot.java, src/main/java/io/jenkins/update_center/json/UpdateCenterRoot.java, src/main/java/io/jenkins/update_center/wrappers/VersionCappedMavenRepository.java, src/test/java/io/jenkins/update_center/HPITest.java
Plugins can declare any version number as a core dependency in their metadata.
If a plugin were to specify an incremental or similar non-release, e.g., due to an accidentally merged and released PR depending on future core features, this will result in unpredictable behavior (usually errors of some kind).
Therefore filter out plugins that specify core dependencies that look like irregular releases (RC, incrementals, snapshots, …)
Currently published plugin releases this applies to (and that would be removed):
https://updates.jenkins.io/download/plugins/build-symlink/ 1.0 (2.185-rc28469.6af78cb11bf8)
https://updates.jenkins.io/download/plugins/jcaptcha-plugin/ 1.0 (1.416-SNAPSHOT)
https://updates.jenkins.io/download/plugins/sshd/ 3.0.1 (2.282-rc30905.2ddf35821c11)
Impact should be …
=> Validate core dependencies

resources/artifact-ignores.properties
This seems to be causing users a lot of pain in https://github.com/jenkinsci/gitlab-plugin/issues/1419, so let's revert the upgrade in https://github.com/jenkinsci/jersey2-api-plugin/pull/60 and suspend the problematic version from distribution.
=> Suspend jersey2-api 2.39-1 from distribution

resources/artifact-ignores.properties
See https://github.com/jenkinsci/h2-api-plugin/pull/9
Is it possible to fix this? Given it's been pushed to the maven repository?
i.e. renovate / dependabot might just keep offering the new version?
=> Ignore h2-api@10.v8dd81336a_ede

resources/artifact-ignores.properties, resources/deprecations.properties
We got a complaint via GitHub Trust & Safety about code copyrighted by BMC Software Inc in one of our plugin repos, specifically https://github.com/jenkinsci/compuware-common-configuration-plugin/blob/85e15ffc9a2987453f61a1f41f91d7fe109d5636/src/test/java/com/compuware/jenkins/common/configuration/HostConnectionTest.java#L56 and https://github.com/jenkinsci/compuware-common-configuration-plugin/blob/85e15ffc9a2987453f61a1f41f91d7fe109d5636/src/test/java/com/compuware/jenkins/common/configuration/HostConnectionTest.java#L256 (yes, really).
Out of an abundance of caution I recommend we suspend all of their plugins' distribution.
=> Suspend all BMC/Compuware plugins

resources/artifact-ignores.properties
Mostly undo #692.
Related to https://github.com/jenkins-infra/helpdesk/issues/3461.
=> Restore BMC plugins except releases with non-free licenses

resources/artifact-ignores.properties
The Delphix plugin is out of date and requires significant attention. Our goal is to temporarily discontinue its distribution until it's rewritten to our higher standards. 
It's my understanding that this page will become unavailable on merge: https://plugins.jenkins.io/delphix/
=> Discontinuing the Delphix plugin

resources/artifact-ignores.properties
Version numbers are fixed, and #673 makes suspension of the originally offending version unnecessary.
Reverts #621.
=> Restore mergebase-sca distribution

resources/allowed-github-topics.properties
many plugins provide credential types or are credential stores.   if they are labeled as such we should have an easy way to discover them.
as per https://www.jenkins.io/doc/developer/publishing/documentation/#labeling-plugins submitting a PR to add `credentials` to the allow list of labels.
Not sure where the plugin page gets the text labels to search specific labels from in order to change that too :-/
=> add credentials to the allowed topics

resources/artifact-ignores.properties
I have adopted the plugin so it now as an active maintainer and version 2.3.1 was released that fixes security vulnerabilities SECURITY-2987 and SECURITY-2986 .
=> Revert #678 to reinstate keycloak plugin.

resources/artifact-ignores.properties
I would like to unpublish `headspin` plugin(https://plugins.jenkins.io/headspin).
=> Unpublish `headspin` plugin

resources/artifact-ignores.properties
Artifacts were released only for testing fix https://github.com/jenkinsci/sidebar-link-plugin/pull/60 and should not be listed in https://plugins.jenkins.io/sidebar-link/releases/ as new valid release is published already.
New artifact is not listed as the most recent version so that's why it is not available at update center.
=> Remove invalid sidebar-link releases

resources/artifact-ignores.properties
https://github.com/jenkinsci/synopsys-polaris-plugin/commit/7a0327cf352ace3a922aea9e3239958644fad706 changed the license from Apache 2.0 to a non-free license.
By the [Jenkins hosting guidelines](https://www.jenkins.io/doc/developer/publishing/preparation/#license), all plugins have to be licensed under an [OSI-approved](https://opensource.org/licenses/) license.
To restore distribution, revert the license changes made in https://github.com/jenkinsci/synopsys-polaris-plugin/commit/7a0327cf352ace3a922aea9e3239958644fad706.
Versions released under a non-free license remain suspended.
cc @DanaMaxfield @sig-saraf @sig-sshreyas @blackduck-serv-builder
=> Suspend specific versions `synopsys-polaris` due to OSI license violation

resources/warnings.json
[SECURITY-2709](https://issues.jenkins.io/browse/SECURITY-2709)
This was corrected by https://github.com/jenkinsci/visualexpert-plugin/commit/25eda3057ce2dd5274b8c3c26a92257eeedaddbb and was released in v2.1
I tested the fix locally.
=> SECURITY-2709 Remove warning from visualexpert

resources/warnings.json
The vulnerability has been fixed in this [PR](https://github.com/jenkinsci/opsgenie-plugin/pull/8).
You can check the latest plugin from [here](https://updates.jenkins.io/download/plugins/opsgenie/). e.g. `1.10`
=> SECURITY-1877 Remove warning from opsgenie-plugin

resources/artifact-ignores.properties
We plan to push/release an updated version of our Delphix plugin v3.0.0 tomorrow. 
This will replace the existing (but currently hidden) Delphix Plugin. 
This PR is meant to revert the change I made back in March. https://github.com/jenkins-infra/update-center2/pull/695
Ideally, we merge this PR around the same time [the PR here is merged. ](https://github.com/jenkinsci/delphix-plugin)
=> Re-releasing the Delphix Plugin

resources/artifact-ignores.properties
[Azure updates June 14, 2021](https://azure.microsoft.com/en-us/updates/azure-dev-spaces-retired-on-may-15-2021/) announces the retirement of Azure Dev Spaces May 15, 2021.
The [Microsoft learn site](https://learn.microsoft.com/en-us/previous-versions/azure/dev-spaces/) points to "Bridge to Kubernetes" as the replacement.
[JENKINS-71776](https://issues.jenkins.io/browse/JENKINS-71776) asks to suspend azure-dev-spaces becuse the service is no longer available.
=> Suspend Azure Dev Spaces plugin, service discontinued

resources/warnings.json
This was corrected by https://github.com/jenkinsci/sumologic-publisher-plugin/commit/cdb7432f4a634af7e1333374626f06aa4a5de9dd and was released in v2.2.4
I tested the PR locally
=> SECURITY-3117 Remove warning from sumologic-publisher

resources/deprecations.properties
- Jenkins UI no longer shows balls
- Current passing build status is already green
- This plugin doesn't load anymore on Java 17 with a reflection error
https://giphy.com/gifs/star-trek-qH7J4EXzSCmBy
=> Deprecate Green Balls

resources/wiki-overrides.properties
This PR removes the wiki override in order to use the GitHub README as plugin description on plugins.jenkins.io instead of the content of https://wiki.jenkins.io/display/JENKINS/Github+Custom+Notification+Context+SCM+Behaviour+Plugin
Ref: https://github.com/jenkins-infra/helpdesk/issues/3770
=> Remove wiki override for `github-scm-trait-notification-context`

resources/wiki-overrides.properties
This PR removes the wiki override in order to use https://github.com/jenkinsci/sonarqube-plugin/blob/master/README.md as plugin description on plugins.jenkins.io instead of the content of https://wiki.jenkins-ci.org/display/JENKINS/SonarQube+plugin
Ref: https://github.com/jenkins-infra/helpdesk/issues/3777
=> Remove wiki override for `SonarQube`

resources/artifact-ignores.properties
The INFRA- tickets were moved to GitHub, trying to access them leads to Jira login page.
=> Use public URLs for suspension reasoning

resources/warnings.json
The issue https://issues.jenkins.io/browse/SECURITY-1025
The release
* https://github.com/jenkinsci/batch-task-plugin/releases/tag/1.398.v550a_8e8ca_e5f
* https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/batch-task/1.398.v550a_8e8ca_e5f/
=> [SECURITY-1025] Remove warning from batch-task

resources/deprecations.properties
This plugin is deprecated due to open security vulnerabilities and readily available replacements provided with currently supported operating systems.
There are two open security vulnerabilities.  The plain text credentials storage security vulnerability was published in October 2017.  The CSRF vulnerability and missing permission check security vulnerability was published in February 2022.
The `scp` command is available on all the operating systems that Jenkins supports.  Unix variants include `scp` with the OpenSSH commands.  Windows includes `scp` with their port of OpenSSH.  The `withCredentials` Pipeline step supports ssh private keys so that users can more safely call `sh` steps that perform `scp` operations.
The plugin was last released in January 2011.  The last commit with any …
=> Deprecate scp plugin

resources/artifact-ignores.properties
https://github.com/jenkins-infra/helpdesk/issues/3856 explains that the Confluence publisher plugin uses a dependency that is not open source licensed.
The Confluence publisher libraries are Atlassian licensed including:
* com.atlassian.confluence:confluence-java-api:7.14.0
* com.atlassian.confluence:confluence-rest-client:7.14.0
* com.atlassian.confluence:confluence-rest-serialization:7.14.0
* com.atlassian.confluence:confluence-rest-api:7.14.0
The Atlassian license is not an open source license.  Refer to https://www.atlassian.com/legal/software-license-agreement for the details of the license.
https://www.jenkins.io/project/governance/#license says that the Jenkins project requires plugins that it distributes to be open source, including their dependencies.  When a closed source …
=> Suspend distribution of Confluence publisher plugin

resources/artifact-ignores.properties
Database is discontinued since more than 10 years.
https://dbdb.io/db/drizzle
I don't see any point to keep it on the list of database plugins.
https://github.com/jenkinsci/database-drizzle-plugin
I can also submit an helpdesk ticket to archive the repo
=> Removal of database-drizzle

resources/artifact-ignores.properties
This PR removes `plasticscm-mergebot` (https://github.com/jenkinsci/plasticscm-mergebot-plugin) from the update center. The plugin is now deprecated https://github.com/jenkinsci/plasticscm-mergebot-plugin/pull/6 and its functionality is merged into https://github.com/jenkinsci/plasticscm-plugin.
=> Deprecate `plasticscm-mergebot` in artifact-ignores.properties

resources/artifact-ignores.properties
Hello!
We accidentally released the [24.1 version](https://repo.jenkins-ci.org/ui/repos/tree/General/releases/org/jenkins-ci/plugins/hp-application-automation-tools-plugin/24.1/hp-application-automation-tools-plugin-24.1.jar?clearFilter=true) of the [plugin](https://plugins.jenkins.io/hp-application-automation-tools-plugin) too early, while trying to do a dry run.
We would like this version to be removed or at least not to be available for use.
On the 12th of march we will need to release the same version of the plugin -- 24.1. Can this be done, since here it will be ignored? Or we will have to make the release with a new version?
Thank you!
=> Delete/Ignore version 24.1 of the hpaat plugin

resources/warnings.json
Try to remove warning.
https://issues.jenkins.io/browse/JENKINS-69980
=> [SECURITY-2716] Update warning range as the fix went into 0.0.8

src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
Amends #364 and https://github.com/jenkins-infra/update-center2/pull/673.
This filters out paths that include a bunch of characters that indicate something has gone wrong during the Maven release process. While there are already several characters (notably unprintable ASCII, originally motivating this filter) being filtered, this adds more, based on what is actually used: Keep basic ASCII letters, digits, `_+.-`, as well as `/` since we're looking at paths at this point.
Compared to the current filter, this doesn't remove anything that is being distributed at the moment.
Also fix the message, it hasn't been correct in a long time, most of the stuff filtered is due to `%` from percent-encoded characters.
=> Further limit allowed characters in file path

src/main/java/io/jenkins/update_center/json/PluginVersions.java
The file [plugin-versions.json](https://updates.jenkins.io/current/plugin-versions.json) is the base for sorting the releases of a plugin on the plugins page at https://plugins.jenkins.io 
The sorting with string causes wrong ordering in some cases as described in https://github.com/jenkins-infra/plugin-site/issues/1336
By sorting with the Comparator of VersionNumber we get the same sorting as in other places.
=> sort according to VersionNumber comparator

src/main/java/io/jenkins/update_center/GitHubSource.java
Apparently, GitHub silently (?) changed how unauthenticated API use works: Rather than get an authentication challenge, after the rate limit is reached, an error is returned.
This PR implements preemptive authentication.
=> Fix GitHub authentication

src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
While the ability to host private update sites is explicitly _not_ a goal of this tool, this still makes it easier to use it in such situations:
* Allow overriding the Artifactory URL, Artifactory API URL, and Maven repository name
* Authenticate for artifact download
Additionally, this change should make it easier to respond to Artifactory problems like https://groups.google.com/g/jenkinsci-dev/c/4sgBC1crUJw/m/jrRxMKhKAAAJ, as only a few environment variables need to be set, rather than the code needing to be changed. I tested this with a recent private security fix staging repo and got only those fixes as part of the output, just by specifying `ARTIFACTORY_REPOSITORY`.
=> Make it easier to use with custom repositories

site/publish.sh
This PR allows synchronizing the content of updates.jenkins.io to the new Azure File Share and CloudFlare R2 buckets I've put in place for the migration of this service from the current VM to an high availability service on publick8s.
This migration will allow us to reduce our AWS cost by a third, thanks to the free outbound bandwidth of CloudFlare R2.
It will also allow us to benefit from a distributed service thanks to mirrorbits, and (later) the use of a bucket in each of the 6 regions offered by CloudFlare for its buckets: https://developers.cloudflare.com/r2/reference/data-location/#available-hints.
For this sync I'm using the `aws-cli` and `azcopy` tools now installed on trusted agent since https://github.com/jenkins-infra/jenkins-infra/pull/3099
For `aws-cli`, it's using a non …
=> Also sync content into Azure File Share and R2 buckets

resources/artifact-ignores.properties
https://github.com/jenkins-infra/helpdesk/issues/3989 describes the situation.  The license of the relevant library was changed for the version that is included in the delphix plugin 3.2.0.
=> Suspend 3.0.x and 3.1.x delphix plugin versions

site/publish.sh
This PR changes the SSH/Rsync user for `pkg.origin.jenkins.io` (`updates.jenkins.io`) to ensure we can only let `www-data` to read-only files (through group membership) on both `/srv/release/jenkins/**` and `/var/www/**`.
Note: the permanent agent of trusted.ci where this script runs is already setup to log-in as `mirrorbrain` user:
```
jenkins@agent:~$ ssh mirrorbrain@updates.jenkins.io echo Hello
Hello
```
Once this PR is merged, a manual operation to set up permissions properly is required.
=> hotfix(publish) change the SSH/rsync user for connecting to the `pkg` VM (`updates.jenkins.io` and `pkg.origin.jenkins.io`)

site/publish.sh
Follow up of #770 and coupled with https://github.com/jenkins-infra/mirror-scripts/pull/18
=> hotfix(publish.sh) tune rsync permissions for updates.jenkins.io

site/publish.sh
This PR skips azcopy version check which we don't care about as its version is tracked by updatecli.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414
=> chore: skip azcopy version check

resources/warnings.json
This was corrected by https://github.com/jenkinsci/tap-plugin/pull/37 and was released in v2.4.2
=> SECURITY-3190 Remove warning from TAP

resources/artifact-ignores.properties
The 7.0.0 release of the [Datadog plugin](https://github.com/jenkinsci/datadog-plugin) introduced a [major regression](https://github.com/jenkinsci/datadog-plugin/issues/423) and needs to be removed from the Update Center's output
=> Remove datadog@7.0.0 plugin from distribution due to regression

resources/artifact-ignores.properties
More info: https://help.perfecto.io/perfecto-help/content/perfecto/integrations/jenkins_plugin.htm#
Important: As of May 24, 2024, the Perfecto Jenkins plugin will be deprecated. Current plugin installations will continue to work, but going forward, Perfecto will no longer provide bug fixes and maintenance services for this plugin. As an alternative, you can create a Jenkins pipeline with Perfecto Connect. To learn more, see [Jenkins plugin](https://help.perfecto.io/perfecto-help/content/perfecto/integrations/jenkins_plugin.htm#) > Step-by-step instructions > 4 | Work with Advanced usage scenarios > Create a Perfecto Connect pipeline.
=> deprecating perfecto plugin

resources/warnings.json
This vulnerability was fixed with v2.0 a long time ago, but when updating warnings, we forgot to add the latest affected version.
=> Last Version was missing

site/publish.sh
While working on https://github.com/jenkins-infra/update-center2/pull/777 for the [Update Center migration to a mirror system](https://github.com/jenkins-infra/helpdesk/issues/2649), we realized the following problems with the current `publish.sh` script:
- It's hard to test a change until it's in production => we would want to enable/disable some steps to only focus testing on others in order to have enough confidence to merge PRs without breaking the production (neither requiring a fully fledged staging environment)
- There are parameters written in the script itself which requires SREs to open an (untestable for today) PR and merge it as soon as possible when rotating expired credentials/changing configurations of bucket, etc.
This PR is a proposal to solve these issues with:
- Feature …
=> chore(publish) abstract environment variables and introduce feature flags

site/publish.sh
as per https://github.com/jenkins-infra/helpdesk/issues/2649
we add the second cloudflare bucket in east america
=> feat(publish/s3sync): add cloudflare bucket to east america

site/publish.sh
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649
Blocked by https://github.com/jenkins-infra/pipeline-library/pull/854
This PR allows using a dedicated volume for httpd service:
- separated `www-content` & `www-redirections` sources created with a filtered rsync copy from `www2`
- including only the .htaccess files to avoid serving any file from it
- on its own `updates-jenkins-io-httpd` file share, in the same storage account as `updates-jenkins-io` file share used for mirrorbits service
- cherry-picked commit from #776 to allow patching only content in `www-redirections`
- we might need to patch all .htaccess and not only the one at the root, TBD
- mirrorbits and R2 buckets use `www-content` which doesn't contain any .htaccess file as they don't need/can't use/shouldn't have …
=> feat(publish.sh): use dedicated source folder for httpd service including only .htaccess files

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2248481608
This PR is scoped to the new Update Center and fixes the fallback redirection in its httpd component.
The goal of this fallback redirection is to catch any request not meeting the other rewrite rules and redirections and to trigger a redirect to the mirror system (as the file are not served by Apache but by a mirror in the new UC).
Rationale: the Apache `RedirectMatch` directives are processed after all the `RewriteRule`. As such, we want to be sure the fallback has the least priority.
Tested locally with the script from https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2252877808
**Before**
```shell
./.tmp/uc-test.sh http://test.updates.jenkins.io:8080 
= Testing UC behavior on host …
```
=> fix(publish/new UC httpd) use a `RedirectMatch` instead of `RewriteRule` for Apache2 redirection fallback

resources/artifact-ignores.properties
We suspend distribution of plugins that depend on a service that no longer exists or is end of life like:
* https://github.com/jenkins-infra/update-center2/pull/732
* https://github.com/jenkins-infra/update-center2/pull/708
* https://github.com/jenkins-infra/update-center2/pull/676
* https://github.com/jenkins-infra/update-center2/pull/587
This is a similar case to services that are end of life.  Windows is not end of life, but the services required for this plugin have been end of life since at least March 2023. The plugin was deprecated as noted in [README](https://github.com/jenkinsci/windows-slaves-plugin?tab=readme-ov-file#notice-of-deprecation) almost two years ago in [November 2022](https://github.com/jenkinsci/windows-slaves-plugin/commit/cdafd13807267b535b13bbb25d9cc72376aa4594). …
=> Suspend windows-slaves and multi-slave-config plugins

site/publish.sh
This is a minor PR on the `publish` script related to https://github.com/jenkins-infra/helpdesk/issues/2649
The goal is to avoid errors during the trusted.ci publication while a new release of the helm chart `updates-jenkins-io` is deploying.
I had the issue twice which made the update-center job failing twice: it should not have failed as there were running pods during the rollout.
Should not need any tests on the UC itself; just merge it and I'll check the next builds. For the sake of saefty, here are the commands tested with a local connection to the production cluster:
```shell
$ mirrorbits_namespace='updates-jenkins-io'
$ kubectl --namespace="${mirrorbits_namespace}" --no-headers=true get pod --output=name
pod/updates-jenkins-io-httpd-ffd6998bf-hrggk …
```
=> chore(publish.sh) ensure mirror pod retrieval only check Running pods

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2329006497
Verified with success on the trusted.ci agent for sanity:
```
$ echo "${MIRRORBITS_CLI_PASSWORD}" | mirrorbits -h "${MIRRORBITS_HOST}" -a scan -all -enable -timeout=120
Password: ************************************************Scanning westeurope... done
∟ Enabled
Scanning eastamerica... done
∟ Enabled
```
Note: this PR is expecting to fix the update center builds marked in failure since 2 days.
=> chore(publish.sh) fix failing mirrors scan by using `mirrorbits` CLI instead of `kubectl`

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2344340606
The new UC system (in azure) uses the ZIP credential with proper hostname/etc. for rsync (and others).
But the script still specifies (and need) to update the current UC system (in AWS).
=> hotfix(publish) avoid publication failures by using the VM specific hostname

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995
Since https://github.com/jenkins-infra/kubernetes-management/pull/5736, this file share is not used anymore
=> cleanup(publish) remove deprecated azcopy sync redirection (replaced by "redirections-secured")

resources/artifact-ignores.properties
https://github.com/jenkinsci/shared-library-version-override-plugin/blob/786074c9fce7adeaefcdf6b869304be19464c07b/src/main/java/io/jenkins/plugins/shared_library_version_override/FolderConfigurations.java#L78-L80 is unsafe. Since this plugin was first released only today, I propose we're suspend this plugin. Once this issue is resolved, we can restore distribution.
CC @c3p0-maif as maintainer
=> Suspend `shared-library-version-override`

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995
This PR adds a mirrors scan of the secondary mirrorbits instance to ensure everything is up to date and coherent once the publication finished.
The prerequisite https://github.com/jenkins-infra/kubernetes-management/pull/5756 has been deployed with success:
```shell
$ mirrorbits -h updates.jio-cli.trusted.ci.jenkins.io -p 3390 list
Please set the server password with the -P option.
$ mirrorbits -h updates.jio-cli.trusted.ci.jenkins.io -p 3391 list
Please set the server password with the -P option.
```
=> the 2 services are exposed and set up!
----
Note about the performances: I chose not to parallelize as first step. Optimization will have to come later.
The reason is that the switch to S3 copy with …
=> chore(publish) trigger mirror scans of both instances

resources/artifact-ignores.properties, resources/warnings.json
Reverts jenkins-infra/update-center2#802
I am no longer able to reproduce the earlier problem in 19.v3a_c975738d4a_, so restoring distribution.
=> Revert "Suspend `shared-library-version-override`"

resources/artifact-ignores.properties
Being replaced with a rebranded version that is now hosted at https://github.com/jenkinsci/black-duck-sigma-plugin
=> Deprecate and suspend `synopsys-sigma` plugin

site/generate-htaccess.sh, site/publish.sh, site/test/test.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2380569628 and https://github.com/jenkins-infra/helpdesk/issues/4311
After a discussion with @daniel-beck , we realized that some of the issues on the new update center could be solved using smart request distribution on Apache. 
The mix of `mod_rewrite` (`RewriteRule`) and `mod_alias` (`RedirectMatch` ) in the generated `htaccess` files makes the rules ordering hard to determine as Apache evaluates all rewrite rules and apply the module's own internal priority, and then evaluate the redirect matchings.
We were forced to use `RedirectMatch` in https://github.com/jenkins-infra/update-center2/pull/790 to ensure the new UC fallback to `mirrors.updates.jenkins.io` was working as expected without breaking existing …
=> fix(site/htaccess) only use Apache `mod_rewrite` by replacing `RedirectMatch` by `RewriteRule` directives

src/main/java/io/jenkins/update_center/DirectoryTreeBuilder.java, src/main/java/io/jenkins/update_center/IndexHtmlBuilder.java
Fixes https://github.com/jenkins-infra/helpdesk/issues/4311
=> Use absolute URLs for links from download indexes

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/4311#issuecomment-2419583755 (second bullet).
~Closes 810 (as not needed anymore)~
This PR is a follow up of #812  for the new [Update Center](https://github.com/jenkins-infra/helpdesk/issues/2649) using Apache2 + Mirrorbits.
It updates the publication script to serve the following file from Apache instead of mirrors:
- `uctest.json` => solves the HTTP/404 on azure.updates.jenkins.io/whatever?uctest
- `download/**/*.html` (only these files are present: other are sent to get.jenkins.io` => should solve the broken links in these HTML pages
As #812 did add a condition on "the file must not exist in httpd documentroot" to redirect incoming requests to the UC mirrors, Apache will serve these files.
As discussed with @daniel-beck:
- …
=> chore(wrapper/publish) serve `uctest.json` and the HTML in the virtual tree `download/` from Apache instead of mirrors

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2444529367
This PR introduces the following changes:
- Only copy the JSON files in the Update center mirrors. 
- Note: rsync adapted to use extra exclude/include flags to keep excluding the unwanted directory trees which may contain (unwanted) JSON files such as `updates/`
- Changes the Apache config of the new UC in Azure to:
- Instead of "fallback to mirror if file is absent from docroot":
- Send ALL JSON files to the mirrors (whether they are UC metadatas or crawler `updates/*.json`)
- Also send the `updates/*.html` requests to mirrors
- Copy all data to Apache (all JSON, etc.) to ensure we have directory listing
- Note: we have to do the same on the crawler publication script if it works as expected
=> we …
=> chore(wrappers - publish.sh) only send JSON files to mirrors

site/publish.sh
As per <>
we want https://azure.updates.jenkins.io/current/update-center.json.html redirected to https://mirrors.updates.jenkins.io/current/update-center.json.html (and then to a mirror close to the HTTP client's location).
This PR is a fixup of #816 with the following corrections:
- Simplify the 2 "additional" redirection rules (added to the new Azure Apache) into a single one to redirect ALL `.json.html` files to mirrors (not only `updates/` ones)
- And of course, copy these files to mirrors
Note: tested with the integrated test, same as #816 (not commited to avoid breaking the actual UC):
```diff
diff --git a/site/generate-htaccess.sh b/site/generate-htaccess.sh
index 42b48ea..628fe5c 100755
--- a/site/generate-htaccess.sh
+++ b/site/generate-htaccess.sh
@@ -135,4 +135,8 @@ RewriteRule …
```
=> chore(wrappers/publish) new Azure UC: send all `.json.html` requests to mirrors

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/4375
This PR aims at fixing the issue:
- `azcopy sync` does not provide any symlink option
- We cannot use `azcopy copy` (which has symlinks options)
So we take advantage of `rsync` to do the "symlink dereferencing" for us.
Note: the impact in timing can be ignored as this task is in parallel of S3 which takes WAY more time
=> chore(wrappers/publish) ensure Apache has access to symlinked folders

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/2649
This PR ensures that mirrorbits does not mark files with "Hash Mismatch" or "File size mismatch" during 8-9 minutes (until the next "mirrorbits Scan Repository" is performed).
It should avoid sending all traffic to the fallback during these (long) minutes.
=> chore(wrappers/publish) ensure mirrorbits scans local files before scanning mirrors

site/publish.sh
Reverts jenkins-infra/update-center2#820
Because the rsync fails with:
```
symlink has no referent: "/home/jenkins/agent-workspace/workspace/update_center/www2/current/updates"
```
=> Revert "chore(wrappers/publish) ensure mirrorbits scans local files before scanning mirrors"

site/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/4402#issuecomment-2498467862
This PR adds 3 new rsync targets, which goal will be to replace the current `azcopy`  targets as soon as possible.
It will populate these elements in parallel of the existing ones to avoid disrupting the existing production (we'll switch to the new populated data later).
Checks:
- Credentials have been updated in trusted.ci.jenkins.io.
- Routing has been verified on the `agent-1` permanent agent
=> chore(wrappers/publish) add 3 new rsync targets on the new data service

site/publish.sh
Reverts jenkins-infra/update-center2#828
As soon as https://github.com/jenkins-infra/kubernetes-management/pull/5959 is deployed, we can safely start using rsync tasks to fill the NFS shared volume
=> Revert "Revert "chore(wrappers/publish) add 3 new rsync targets on the new data service""

site/publish.sh
as per https://github.com/jenkins-infra/helpdesk/issues/4401#issuecomment-2515106384
add archives.jenkins.io to the parallel steps for rsync in order to add it as a failback mirror
depends on https://github.com/jenkins-infra/charts-secrets/pull/34
=> feat(publish): add archives.jenkins.io in the rsync process for update-center

resources/artifact-ignores.properties
protecode-sc plugin is no longer supported or developed at all and should be removed.
=> Removal of protecode-sc plugin

site/generate.sh, src/main/java/io/jenkins/update_center/MetadataWriter.java, src/main/java/io/jenkins/update_center/json/WithSignature.java, src/main/java/io/jenkins/update_center/util/Timestamp.java
`Last-Modified` headers of the metadata files are no longer a reliable indicator of age, as these are different between the different hosts that respond to those requests since recent infra changes (archives/fallback vs. CF).
Downloading all of `update-center.actual.json` to get the timestamp from https://github.com/jenkins-infra/update-center2/pull/636 is impractical, and wasteful if done repeatedly in a short amount of time.
So this PR adds the new file `timestamp.txt` that has the same content as the value of `.generationTimestamp` in `update-center.actual.json` would be.
=> Generate `timestamp.txt`

resources/artifact-ignores.properties
These plugins were published during an earlier phase of development but have seen been renamed for consistency or combined for technical reasons.
=> Block unneeded AWS Java SDK 2 plugins

.mvn/maven.config, Jenkinsfile, pom.xml
This lets the project use Java 21. 
As the project deals a lot with String, this updates could help as the recent versions improved the memory management for that.
It opens us to bump support-log-formatter and version-number next (or let dependabot do it).
Once we have the build setup with this, we can go through the code and update API calls, removing deprecated onces, use. try-with-resources, records, and other few cleanups.
=> Update JVM from 11 to 21

site/publish.sh
as per https://github.com/jenkins-infra/helpdesk/issues/4500#issuecomment-2650386390
we need to provide that parameter for the call to go through on cloudflare R2 with the aws cli new version released here https://github.com/jenkins-infra/packer-images/pull/1723
=> feat(publish.sh): adding CRC32 checksum algorithm paramter on the aws cli call to cloudflare R2

resources/artifact-ignores.properties
No sources corresponding to this plugin's releases are still available in the repository at https://github.com/jenkinsci/simplify-qa-connector-plugin/
Looks like the maintainers simplified a little too much :trollface:
=> Suspend `simplify-qa-connector`

resources/artifact-ignores.properties
It prevents instances from starting up (JENKINS-75425). Fixed by https://github.com/jenkinsci/audit-trail-plugin/pull/170
=> Exclude audit-trail version 393.v6a_3d1e251274 from distribution

site/publish.sh
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2755171440 and https://github.com/jenkins-infra/helpdesk/issues/4610
This PR stops copying UC metadata to the `pkg` VM since it does not host any update center site anymore.
=> chore(publish) stop copying UC site to (aws.)updates.jenkins.io VM (also known as `pkg`)

src/main/java/io/jenkins/update_center/json/WithoutSignature.java
Amends https://github.com/jenkins-infra/update-center2/pull/858.
With the update of `fastjson`, secondary files ended up empty.
=> Fix file writing

src/main/java/io/jenkins/update_center/ArtifactoryRepositoryImpl.java
By default, redirects are not followed, and HTTP 302 is considered a failure to download a few lines down.
This looks like it would explain the recent problems with cached download failures.
Amends https://github.com/jenkins-infra/update-center2/pull/840
CC @alecharp
=> Follow HTTP redirects

resources/warnings.json
Superseed https://github.com/jenkins-infra/update-center2/pull/855
The vulnerability was corrected by https://github.com/jenkinsci/copy-data-to-workspace-plugin/pull/3 & https://github.com/jenkinsci/copy-data-to-workspace-plugin/pull/23 which was released in `63.ve6c51d760236`
=> SECURITY-1966 Remove warning from copy-data-to-workspace-plugin

resources/artifact-ignores.properties
The SmartBear CrossBrowserTesting [About page](https://support.smartbear.com/crossbrowsertesting/docs/about.html) and [documentation index](https://support.smartbear.com/crossbrowsertesting/docs/index.html) say:
> CrossBrowserTesting will no longer be available on July 31, 2023.
Jonathan Parrilla of SmartBear requested that the repository be archived in a [message](https://groups.google.com/g/jenkinsci-dev/c/8VMFBfcmOu4/m/zbnWkyPdAAAJ) to the Jenkins developers mailing list
Let's suspend distribution since the service has been unavailable for almost 12 months.
=> Suspend crossbrowsertesting plugin - service discontinued

resources/warnings.json
Corrected in https://github.com/jenkinsci/image-tag-parameter-plugin/pull/134 and https://github.com/jenkinsci/image-tag-parameter-plugin/pull/135
Released as https://github.com/jenkinsci/image-tag-parameter-plugin/releases/tag/image-tag-parameter-3.0
=> Remove warnings from image-tag-parameter

resources/artifact-ignores.properties
commons-lang is EOL since 2011 and vulnerable (CVE-2025-48924). The library plugin is not used by any other plugin. Due to ongoing activities to remove commons-lang from core and all plugins it will also not be needed via an implied dependency.
=> suspend commons-lang

resources/deprecations.properties
The [BMC AMI DevOps for Change Manager for IMS TM Plugin](https://plugins.jenkins.io/bmc-change-manager-imstm/) was deprecated because it included the Jenkins test harness in its most recent release.  The deprecation is in pull request:
* https://github.com/jenkins-infra/update-center2/pull/864
A maintainer has arrived, @mcohen11 , and has merged the pull request that removes the Jenkins test harness.  That is pull request:
* https://github.com/jenkinsci/bmc-change-manager-imstm-plugin/pull/13
The plugin has been updated to require Java 17 and a modern Jenkins version with pull request:
* https://github.com/jenkinsci/bmc-change-manager-imstm-plugin/pull/23
The new release is available from the update center as shown by the [mirrorlist](https://get.jenkins.io/plugins/bmc-change-manager-imst …
=> Remove deprecation of bmc-change-manager-imstm

site/publish.sh
Ref. https://github.com/jenkins-infra/helpdesk/issues/4767#issuecomment-3184312247
This PR has been tested on trusted.ci using the source branch for at least 2 weeks.
The goal of this PR are:
- Fix the hostname of the `mirrorbits` API server (changed from custom hostname to an Azure-defined by convention).
- Populate`get.jenkins.io` directly from the trusted.ci permanent agent using the new NFS share used by mirrorbits. 
- The final goal is to stop sending files to the `pkg.origin.jenkins.io` VM (unless it is a package but that should be the jenkins-infra/release responsibility). But it will require a subsequent PR to remove the "rsync copy + remote SSH script" in favor of "rsync to archives.jio" step.
Task lists:
=> chore(publish) copy released plugins to get.jenkins.io directly
